= Australien

== Mein Australienaufenthalt 2004

An dieser Stelle möchte ich ein paar Infos über meinen Australienaufenthalt kund tun, d.h. wie der aktuelle Stand ist, was ich machen will und später auch "live" Reiseberichte, d.h. wo ich grad bin, was ich mache. Ich hoffe, dass ich die Möglichkeit habe, auch Bilder hochzuladen, was ich dann tun werde…
Ihr findet in meiner /http://www.marc-schumacher.de/links/index.php?id=47[Linksammlung zu Australien], die ich von nun an regelmässig updaten werde, immer neue Links zu den Orten, die ich hier nenne.

=== 25. Februar 2004, 10:00 - Flug reserviert

Ich habe gerade meinen Flug soweit es ging reserviert. Sollte nichts dazwischen kommen, werde ich am 01. September 2004 von Düsseldorf (Flug EK 056) mit den http://www.emirates.com/[Emirates] losfliegen. Dort komme ich dann um 23.40 Uhr Ortszeit (20.40 Uhr in Deutschland) an. Netterweise spendiert die Airline in http://www.dubaiairport.com/[Dubai] dann einen Hotelaufenthalt, da der nächste Flug erst am 2. September um 10.15 Uhr Ortszeit (07.15 Uhr in Deutschland, Flug EK 412) wieder los geht; das ist ja schon mal ganz nett. Um 06.05 Uhr Ortszeit (20.05 Uhr in Deutschland) werde ich dann hoffentlich unbeschadet in Sydney landen. Zurückkommen werde ich am 28. September. Der Flug von Sydney nach Dubai geht am 27. September um 21.50 Uhr (11.50 Uhr in Deutschland, Flug EK 413). Am 28. September werde ich um 05.30 Uhr Ortszeit (02.30 Uhr in Deutschland) landen. Weiter geht es dann um 08.50 Uhr (05.50 Uhr in Deutschland) mit dem Flug EK 055. Um 12.55 Uhr werde ich dann am Sonntag in Düsseldorf landen. Reisepässe sind übrigens ziemlich teuer; ich musste grad 26 EUR zahlen!

=== 03.März 2004, 10:00 - Arbeit bei Jillian

Habe heute bescheid bekommen, dass ich auf der http://www.leconfieldridenatural.com/[Farm von Jillian] gegen Kost und Logie arbeiten kann. Im Gegenzug lehrt sie mir das http://www.parelli.com/[Natural Horsemanship]. Bin total happy!

=== 06.April 2004, 10:00 - Formalitäten

Reisepass und int. Führerschein habe ich jetzt abgeholt. Die Versicherung und der Kurs bei Jillian sind gebucht. Jetzt ist organisatorisch schon ne Menge geregelt…

=== 04. Mai 2004, 10:00 - Flug gebucht

Der Flug ist gebucht und fest, das Visum habe ich auch. Jetzt kann es so langsam los gehen. Ich muss nur noch meine Wohnung untervermietet bekommen; dann bin ich glücklich…

=== 21. Juli 2004, 12:40 - Jobsuche

Heute ist mir bewußt geworden, daß es wohl doch nicht ganz so einfach sein könnte, einen Job zu finden, bei dem ich etwas mit Pferden machen kann. Insbesondere die Idee, nach dem Cowboytraining auch dort anfangen zu können, könnte sehr leicht in die Hose gehen. Neben leichter Panik, macht sich bei mir jetzt, obwohl ich grad an meiner Diplomarbeit schreibe, Aktionismus breit. Ich werde mich mal in ganz Australien nach etwaigen Anbietern von Reittouren umhören und schauen, ob sich da nichts finden lässt.
Außerdem habe ich Jill noch mal angeschrieben und nach näheren Informationen gefragt. Mal sehen, was sich so ergibt…

=== 22. Juli 2004, 11:47 - Nachricht von Jillian (hooray!)

Good news, everyone. Ich hab heute Mail von Jillian, der Besitzerin der Farm, bei der ich anfangen will, bekommen. Hatte schon gedacht, dass sie ein bisschen genervt von mir war und jetzt gar nicht mehr schreibt; glückleicherweise hat sie es doch getan .
In der Mail wurden ein paar Unklarheiten bereinigt, und zwar folgendes:
- die Zeit, wie lange ich dort arbeite, ist nicht begrenzt, nur von Januar bis Mai ist der Laden geschlossen
- wir werden nicht, wie erwartet im Zelt, sondern in einer Scheune schlafen können; dort scheint es ein paar “living quarters” zu geben
- Freizeit hat man auch
- Elektrizität ist auch vorhanden, super, sonst hätt ich ein Problem mit der digitalen Kamera…
- wie sie schon vorher mal geschrieben hat, ist es dort wohl nicht ganz so warm, es kann nachts bis zu minus 5 Grad werden
Trotzdem werde ich mich noch mal sicherheitshalber auch woanders umsehen, da mir ein paar Forenbeiträge nicht so viel Mut gemacht haben…

=== 02.08.2004, 17:08 - Untermiete meiner Wohnung

Heute hat sich endlich jemand gemeldet, der ggf. während meiner Abwesenheit in meine Wohnung einziehen würde. Das ist schon mal eine sehr gute Nachricht, wenn ich nämlich keine Interessenten gefunden hätte, hätte ich nicht fahren können. Ist schon mal toll, dass das geklappt hat.

=== 12.08.2004, 13:10 - Flug bezahlt

Gestern habe ich endlich meinen Flug komplett bezahlt, d.h. es kann jetzt langsam los gehen. Bin schon etwas nervös…

=== 18.08.2004, 15:13 - Untervermietung und Job

Ich habe gerade eben den Mietvertrag an meinen Zwischenmieter verschickt. Außerdem habe ich gestern die Zusage erhalten, dass ich zumindest für die ersten zwei Monate nach Australien einen Job bei der Firma INFORM haben kann. Soweit sind also meine finanziellen Sorgen aus dem Weg geräumt, soweit das Geld in Australien dann reicht.

=== 30.08.2004, 16:30 - Wohnung blitzeblank, Backpackers gebucht

Jetzt ist meine Wohnung fast übergabebereit. Es müssen nur noch die Küche und das Bad gereinigt werden und die ganzen Kisten gelagert werden, dann kann ich meine Wohnung morgen für knapp drei Monate meinem Zwischenmieter übergeben. Was für ne Arbeit! Aber dann kommt man wenigstens mal dazu, auszumisten
Nach einem Telefonat mit Steph, meinem Studienkollegen, der zusammen mit mir nach Sydney fliegt und dort 1/2 oder ggf. sogar ein ganzes Jahr verbringt, werden wir wohl doch nicht sofort in einer WG unterkommen, sondern müssen die erste Zeit in einem Backpackers verbringen. Dank eines Tipps von Julia, der besten Freundin von Judith, werden wir wohl in “The Palm” unterkommen. Wer mal schauen möchte, was uns da erwartet, kann sich unter http://www.thepalmsbackpackers.com[http://www.thepalmsbackpackers.com] kundig machen . Sieht sehr nett aus, ich freu mich schon.

=== 03.09.2004, 22:43 - Angekommen

Mein Flug am ersten September ging um 15.15h. Um noch einen Platz am Emergency Seat zu bekommen, musste ich aber schon um etwa 12h da sein; und ich hatte Glück: sogar Steph, der Studienkollege, der für ein Jahr nach Sydney geht und dort studiert, hat neben mir am Emergency Exit einen Platz bekommen.
Der Abschied mit Judith war zum Glück nicht so lang, so dass es uns zwar trotzdem nicht leichter fiel, man das ganze aber nich so breit getreten hat.
Meine erste Station sollte Dubai sein: der Flug dauert etwa 6h. Das tolle war ja, dass ich einen Stopover-Flug hatte, also ein Zimmer in Dubai von den Emirates spendiert bekommen habe. Der Flug ging recht schnell um; ich hab mich einige Zeit mit einem Mädel aus Köln unterhalten, das Sonderpädagogik in Köln studiert hat und jetzt, wo ihr Freund Diplomarbeit schreibt, auch wegfuhr. Sie ist aber dann weiter nach Bombai geflogen.
Danach musste ich selber schauen, wo ich bleibe: bin also zu den Passport-Kontrollen gegangen und später zu einem Stand vom Emirates-Hotel. Zu dem Zeitpunkt war ich mir noch nicht sicher, ob ich mein aufgegebenes Gepäck noch abholen musste, oder ob es als Transfergepäck am nächsten Tag weitergeleitet werden würde. Zum Glück, musste ich es aber nicht mehr abholen, wie mir der Mann am Schalter gesagt hat. Sehr lustig übrigens; das spiegelt ganz gut meine Englischkenntnisse wider: direkt den ersten Satz, den jemand zu mir gesagt hat und der zudem eigentlich nicht so ganz schwierig war, hab ich nicht verstanden: “Good evening, sir!” - “Äh, pardon…". Ganz schön peinlich…
Naja, zu guter letzt bin wurde ich dann doch noch zum Hotel gebracht; total heftig: der gesamte Flughafen ist ja klimatisiert und ich hab mir schon gedacht, dass es recht warm sein würde, aber als ich dann raus kam, hab ich mich irgendwie gefragt, wo denn der Heizlüfter stand, der mich da anblies, aber da war keiner… Die Hölle! 35 Grad um 23.30h!
Irgendwann kamen wir dann schliesslich aber doch an und da es schon recht spät (0.30h lokaler Zeit) war und mir auch ein Taxi hätte nehmen müssen, hab ichs doch gelassen. Noch eine Coke geholt, Fotos geschossen (waren nicht so toll, daher hab ich sie mal weggelassen) und eine Dusche genommen. Das war der zweite Schock: nicht nur die Luft war höllisch warm, sondern auch das Wasser: ich hab den Hahn auf “Kalt” gestellt, um dann festzustellen, dass es wohl nur die vier Einstellungen “heiss", “sehr heiss", “extrem heiss” und “Brandverletzungen ersten Grades"… Die Stellung “kalt” war aber dann doch okay und ich hatte eine sehr erholsame Nacht.
Am nächsten Tag bin ich dann um 7h aufgestanden, um meinen Flug zu bekommen und Steph zu treffen; ist mir tatsächlich gelungen. Dieser zweite Flug war echt schon hart an der Grenze: 18h und die Zeit wollte nicht vergehen. Das Entertainment-System war dann zu allem überfluss noch bei Steph, mir und zwei anderen Passagieren ausgefallen, so dass wir keine Filme gucken konnte: das war doch eigentlich der Grund gewesen, wieso ich eigentlich nach Australien wollte.
Egal, heute sind wir auf jeden Fall angekommen, mit einem höllischen Jetlag. Ich stehe hier schon etwas schwankend vor dem Terminal des Palms Backpackers, daher nur noch dies: wir haben uns einige Zeit noch durch die Stadt geqäelt, damit wir morgen nicht schon wieder so einen Jetlag haben und sind später zum Hostel zurück gelaufen. Dort haben wir uns abends noch etwas unterhalten (ne Menge junger Backpackers da) und jetzt gehe ich gleich auch ins Bett. Morgen schauen wir uns Sydney mal etwas näher an, u.a. eine Wohnung, die Steph vielleicht nehmen wird. Vielleicht schaffe ich es dann auch mal, eine paar Bilder ins Netz zu stellen. Man kann gespannt sein…

=== 05.09.2004, 21:06 - Erste Bilder

Da ich schon ein paar Fotos gemacht habe hier in Sydney, will ich Euch diese auch nicht vorenthalten. Ihr findet ab sofort unter http://marc-schumacher.smugmug.com/Holidays/29832[http://marc-schumacher.smugmug.com/Holidays/29832] sämtliche Fotos, die von meiner Reise im Internet stehen, unterteilt nach den verschiedenen Stationen. Viel Spass! Alles weitere dann in einem neuen Bericht…

=== 08.09.2004, 11:37 - Handy-Nummer in Aussie

Ich habe mir zu Anfang meines Australien-Aufenthaltes eine Prepaid-Karte hier gekauft. Für alle, die mich mal persönlich an der Strippe haben wollen, bietet sich so die Möglichkeit, mich direkt und persönlich anzurufen. Es wäre allerdings nett, wenn Ihr nicht unbedingt mitten in der Nacht anrufen würdet (zumindest, wenn es hier Nacht ist… ). Der Zeitunterschied beträgt 8 Stunden, d.h. wenn in Deutschland 8 Uhr ist, ist hier 16 Uhr. Eine gute Zeit wäre also zw. früh morgens und spätestens 15h deutscher Zeit.
Meine Nummer in Australien lautet +61424009452, wenn Ihr also von Deutschland aus anruft, wählt ihr 0061424009452, am besten mit einer preiswerten Vorwahl. Einen Link zu einem entsprechenden Tarifrechner findet Ihr auf meiner Seite unter http://www.marc-schumacher.de/australien[http://www.marc-schumacher.de/australien] (Australien Mobilfunk). Die Preise fangen momentan bei 14,7 Euro-Cent an (Vorwahl 01079 bzw. 01071). Ich würd mich freuen, wenn sich jemand mal persönlich melden würde.

=== 08.09.2004, 11:41 - Rund um Sydney

Nach einem Telefonat mit Helen, einer Bekannten von Thiemo aus Aachen, haben wir uns verabredet, am Montag mit ihr in Manly, wo sie momentan mit ihrem Mann wohnt, zu treffen. Leider führte der Jetlag immer noch dazu, dass wir irgendwie kein richtiges Zeitgefühl hatten. Hinzu kam, dass der Wecker, den wir gestellt haben nicht geklingt hat. Dies führte dazu, dass wir 3 Stunden verschlafen haben!! Naja, halb so wild, wir wollten eigentlich vorher noch in die Stadt gehen und ein paar Besorgungen machen, was dann ins Wasser fiel. Glücklicherweise machte so die Verspätung für Helen “nur” eine Stunde aus.
Wir sind also wie üblich von “Kings Cross&quot;, Richtung “Central” losgefahren und dann weiter mit dem Bus zum Circular Quay, von wo die Fähren in die anderen Stadtteile Sydneys losfuhren. Dort angekommen und reichlich hungrig haben wir uns eine Kleinigkeit zum Essen geholt, was nicht ganz billig war, aber was solls. Wir sind dann auf die Fähre Richtung Manly. Als wir losgefahren sind, hab ich noch kurz mit Helen telefoniert. Wir wussten ja nicht, wie sie aussieht und sie hat uns beschrieben, was sie anhatte. Leider scheiterte das ganze an meiner fehlenden Vokabelkenntnis. So ist “purple” kein pink-ähnlicher Rotton, sondern lila.
Nach einer kurzen Begrüßung sind wir dann Richtung Strand gelaufen. Es war zwar nicht sonderlich warm, aber sonnig und toll anzusehen, mit Palmen und allem was man sich so vorstellen kann. Danach sind wir hoch in einen Wald, in die Nähe von einigen Felsklippen, die in Deutschland sicher sehr gut abgesichert gewesen wären. Aber da wir hier in Australien sind, war da gar nix… An einem Aussichtspunkt haben wir uns von Helen erzählen lassen, was wir denn da sehen, welche Stadtteile und dass dies die Tasmanische See sei und nicht der Pazifik. Dann gings weiter durch den Wald, vorbei an einigen verbrannten Sträuchern und einem bildhaft schönen kleinen Teich zurück in die Stadt. Dort vorbei an einem kleinen Markt sind wir in ein Cafe und später zurück Richtung Sydney City per Fähre.
Auf der Fähre hätte man feststellen können, dass sich die Wolken langsam zugezogen haben. Das merkten wir aber erst richtig, als Steph sich plötzlich beschwerte, wer denn da mit Steinen nach ihm werfe. Urplötzlich brach nämlich ein Hagelsturm los, der nicht von schlechten Eltern war. Der Kapitän der Fähre meinte noch, wir sollten in die Fähre kommen, aber wir warteten ab und es kam eine riesige Hagelwand auf die Fähre zu und das bei den Temperaturen! Die Hagel waren riesig, ca. 1-2cm, so dass wir ziemlich froh waren, ihn nicht während unserer Wanderung zu erleben. Später in der City wieder angekommen hat sich der Sturm fast gänzlich verzogen. In der City sind wir durch die George Street zurück nach Kings Cross gefahren und gelaufen und später erschöpft ins Bett gefallen.

=== 08.09.2004, 11:53 - Neue Bilder mal wieder

Ich habe auf meiner Galerie wieder neue Bilder eingestellt. Die Bilder sind von unserer Tour von Manly und den Blue Mountains. Natürlich sind das nicht alle Bilder; das wäre etwas viel, Ihr kennt mich ja…
Ach so, die Bilder findet ihr unter http://marc-schumacher.smugmug.com/gallery/211122[http://marc-schumacher.smugmug.com/gallery/211122].

=== 10.09.2004, 19:33 - Blue Mountains

Nachdem wir uns am Tag zuvor mit Silvia (das war diejenige, die wir auf der Harbour Bridge getroffen haben) verabredet haben, in die Blue Mountains zu fahren, haben wir uns an diesem Morgen getroffen, dies auch zu tun. Wir wollten uns um 9h am Central Station treffen, als ein Anruf von Silvia kam, dass der Zug um 9h auch schon ankäme und wir uns ein bisschen beeilen sollten. Wir sind also wie bekloppt durch den Hauptbahnhof gerannt, da der Bahnsteig vom Blue Mountain-Zug natürlich ganz am anderen Ende des Bahnhofs war. Gerade im letzten Moment sind wir noch in den Zug gehechtet, in der Hoffnung, Silvia dort anzutreffen. Dummerweise stand sie offensichtlich am anderen Ende des Zuges und hat geschaut, ob wir es noch schafften und ist dann nicht eingestiegen. Das führte dazu, dass sie erst den Zug eine Stunde später nehmen konnte.
Wir haben uns nach der zweistündigen Zugfahrt erstmal kundig gemacht, was man denn so ohne etwas gross geplant zu haben, dort unternehmen konnte und zum Glück hatte man einige Möglichkeiten. So gibt es wie in an vielen Orten in Australien Touristen-Busse, die einen zu den Sehenswürdigkeiten kutschierten und auch wieder abholten; dass das ganze mit 22AU$ (Studententarif) etwas teuer war, ist uns allerdings erst später aufgefallen.
Da wir noch etwas Zeit hatten, sind wir ein bisschen durch Katoomba gelaufen und haben uns mit Schals und Sonnencreme eingedeckt. Man mag es kaum glauben: es war Sonnenschein, aber superkalt dort in den Blue Mountains. Und da ich eh schon seit Tagen (wie heute immer noch) eine kleine Erkältung mit mir herumgetragen habe, wollte ich nicht, dass sich das ganze noch verschlimmert.
Nach endlicher Zeit kam dann Silvia an und wir haben uns die Bustickets geholt und sind zu unserer ersten Station gefahren. Katoomba liegt auf einem Gebirgszug und die Busse fahren mehr oder weniger an den Aussichtspunkten vorbei. Man kann aber auch ein paar kleine Wanderungen machen, die alle so im Bereich von 20-120min lagen, also nicht allzu lang. Wie gesagt, wir sind ausgestiegen und haben wieder jemanden aus Deutschland getroffen. Diesmal war es eine allein reisende Informatikerin aus Kölle, die uns den Rest des Tages zusammen mit Silvia begleitet hat.
Das Gelände der Blue Mountains ist superschön (siehe Galerie). Immer wieder fliegen Kakadus und teilweise auch sehr viel buntere Papageienarten. Und wenn man mal einen Aussichtspunkt erreicht hat und nach unten ins Tal sehen kann, sieht man auch hier an allen möglichen Orten diese Papageienarten herumkreisen. Später in der Stadt hat man sogar noch viel mehr auf einem Haufen gesehen.
Wir sind also durch den Wald gewandert zu unserem ersten Aussichtspunkt. Die Aussicht war wirklich atemberaubend. Das tolle war nicht unbedingt die Hügelform oder die tolle Vegetation, sondern das Zusammenspiel von allem und besonders die Weite: man konnte bis an den Horizont schauen und hat kein Ende der baumbewachsenen Hügel erkennen können. Dann -wie bereits erwähnt- die Kakadus und die Klippen; das war wirklich toll. Sowas habe ich vorher noch nicht gesehen. Man kam sich ein bisschen vor wie im Marlboro-Country.
Nach einigen (Panorama-)Fotos sind wir dann weitergewandert, herunter an einem kleinen Wasserfall vorbei, dessen Felsen so aussahen, wie das Gesicht einer Hexe und wieder hoch zu einer Seilbahn, die wir allerdings nicht benutzt haben. Wir sind von dem Ort weiter mit einem “Cabrio-Bus” gefahren, in dem man die Landschaft prima besichtigen konnte. Der Fahrer war ein älterer Australier, der uns eine Menge über die Blue Mountains erzählen konnte. Obwohl wir ihm bestimmt noch viel länger hätten zuhören können, ging es dann doch irgendwann weiter zum Ausgangspunkt. Von dort sind wir dann zum Echo Point gefahren, wo man die Three Sisters (siehe Bild) betrachten konnte. Nach einiger Zeit sind wir einige Treppen zu den Sisters herunter gelaufen. von hier hatte man wieder einen tollen Blick auf die Landschaft. Später gings dann wieder zurück zum Echo Point. Von dort haben wir uns noch einen Aussichtspunkt angesehen, von wo wir dann zurück zu Katoomba City gelaufen sind. Das war ein ganzes Stück, so dass wir erst mal was gegessen haben. Die Bedienung war zwar nicht sonderlich nett (was äusserst selten hier ist), aber dafür war das Essen sehr gut. Später sind wir noch den ganzen Weg zurück zu den Sisters gelaufen, da es sich laut “Lonely Planet” sehr lohnen sollte. Auf den Strassen war fast gar nichts mehr los und als wir wieder am Echo Point angekommen waren, haben wir schon gedacht, dass die Felsen doch nicht beleuchtet wären; zum Glück war das aber ein Trugschluss.
Der Zug, den wir zurück nehmen wollten, war leider schon abgefahren, so dass wir massig Zeit hatten zurück zu laufen. Meine Herren, hätten wir an dem Tag Kilometergeld bekommen, wären wir reich geworden…
Das blöde war ja, dass wir an dem Tag auch noch umziehen wollten von Kings Cross nach Glebe und so mussten wir noch quer durch die City und sind aber später gegen 11.30pm angekommen. Echt ein anstrengender Tag! Aber es hat sich gelohnt!

=== 10.09.2004, 20:07 - Die letzten Tage in Sydney

Jetzt wirds ein bisschen schwierig, da mein Gedächtnis ja wie ein Sieb ist und ich mir keine Notizen gemacht habe, was wir denn alles gemacht haben, will ich hier nur kurz ein paar Sachen erzählen, die mir grad so in den Sinn kommen.
Am Dienstag, den Tag nach unserem Blue Mountains-Ausflug haben wir nicht mehr so viel gemacht. Wir sind noch ein bisschen durch Sydney gewandert und das Wetter war relativ schlecht. Die meisten Sydneysider waren wohl ziemlich begeistert, dass es endlich geregnet hat, weil es dies wohl eine lange Zeit nicht mehr getan hat, aber wir haben uns eigentlich auf ein sonnenreiches Sydney gefreut. Überhaupt wundert mich, dass wir so viel Regen abbekommen haben. Laut einigen Statistiken, soll es in Sydney von 365 Tagen an 350 Tagen kein Regen geben. Wir hatten also die Ehre einen Grossteil dieser Regenzeit innerhalb einer Woche abzubekommen. Naja, da muss man durch. Tamworth soll noch regenloser sein… bin gespannt…
An einem anderen Tag in der Woche sind wir in den Zoo gegangen; dort haben wir zum ersten mal die typischen australischen Tiere zu Gesicht bekommen, u.a. Kängurus, Wombats, Tasmanische Teufel etc. Der Zoo war sehr interessant und schön, leider wurde aber ein Grossteil des Geländes renoviert, so dass wir nur etwa 2/3 des Zoos zu Gesicht bekamen. Die Seilbahn, die hoch zum Zoo führte war eine nette Idee, auch wenn einige Leute weniger die Landschaft ausserhalb genossen, als vielmehr sich mit sich selber beschäftigten, insbesondere die Pärchen, doch dazu vielleicht ein andermal mehr…
An einem anderen Tag waren wir nochmals in Sydney unterwegs und haben uns die Stadt angesehen, aber dazu gibt es nicht so viel zu berichten.
Gestern waren wir im Museum of Art, wo wir uns einige ganz interessante Bilder angesehen haben, teilweise etwas experimentell, aber nicht schlecht. Dort haben wir auch ein Au Pair getroffen, die schon seit sieben Wochen in Sydney weilt und wohl kaum Kontakt zu anderen Leuten gefunden hat. Wir haben sie über eine Anzeige in einem der vielen Internetforen gefunden, e-Mail-Kontakt aufgenommen und getroffen; so einfach kann das gehen…
Morgen werde ich in aller herrgottsfruehe mit einer Mitfahrgelegenheit nach Tamworth fahren. Sie will mich zwischen 7.30 und 8h an unserer Unterkunft abholen. Bin mal gespannt, wie das alles so wird… Ich werde aber berichten…

=== 12.09.2004, 13:53 - Tamworth

Gestern bin ich hier in Tamworth angekommen. Nach etwa 5h Fahrt in den Busch mit der netten Frau aus dem Reisebüro und dem Bruder einer Freundin von ihr. Die Fahrt war ganz interessant. Wir haben erst mal ewig gebraucht, bis wir aus Sydney raus waren und sind dann übers Land. Und das war wirklich Land. Wir haben mal eine kurze Rast gemacht; da fühlte ich mich doch erstaunlich beobachtet… So ist das wohl hier.
Später bin ich dann in Tamworth direkt vor dem Youth Hostel angekommen. In dem Dorm-Room war nur noch eine Holländerin, die anscheinend lieber alleine sein wollte, mir aber trotzdem ein paar Details zu dem Jackeroo-Kurs geben konnte. Sie hat den 5-Tages-Kurs wohl schon gemacht und meinte, dass er wohl ganz toll war, bis darauf, dass das Wetter an zweit Tagen wohl sehr schlecht, kalt und nass war. Ansonsten suchen sie dort wohl tatsächlich noch Mitarbeiter. Die Mitarbeiter sind in eigenen Behausungen untergebracht, d.h. ohne “Familienanschluss&quot;. Finde ich eigentlich ein bisschen schade, da ich schon ganz gerne etwas von dem australischen Familienleben mitbekommen hätte, aber mal sehen. Das positive ist, dass immer etwa 5 externe Arbeiter wie ich es dann auch wäre dort arbeiten würden. Das blöde ist natürlich, dass sie nicht allzu lange bleiben. Ich muss mal schaun, dass ich da trotzdem ein bisschen Anschluss bekomme. Und am Wochenende ist wohl nichts zu tun und die “Arbeiter” fahren wohl nach Tamworth, um Sachen einzukaufen. Soweit ja ganz schön, aber sie bleiben dann meist auch bis Montag dort und verbringen das Wochenende da. Ich hoffe, das war nur ein schlechter Witz: in Tamworth ist so ü-ber-haupt-nix los. Ich war im Tourist Information Center und habe gefragt, was ich denn mal heute machen könnte und der Mensch am Counter fragte erst mal, ob ich denn Country-Musik mögen würde. Das habe ich verneint, woraufhin er meinte, dass jeder, der nach Tamworth kommt, diese Frage mit einem “Ja” beantworten können muss. Egal, ich habe ihn dann gefragt, was man denn sonst so machen könnte. Das Tourist-Info-Center war zwar riesig gross, aber irgendwie hat er für mich nichts gefunden. Und obwohl es ewig viele Pferde auf dem Weg nach Tamworth gab, konnte er mir keinen Stall nennen, der Ausritte organisiert; da sind wir in Aachen etwas besser dran und Aachen ist ja nun mal keine Westernstadt - strange.
Dann kam ich darauf, vielleicht ein bisschen wandern zu gehen, woraufhin mir der Mann nur den Weg zu der grossen goldenen Gitarre nannte, die wohl ansonsten nicht weiter spektakulär war. Dann hab ich ihn darauf hingewiesen, dass ich vielleicht eine kleine Wanderung machen würde, um mir die Gegend anzusehen. Er hat mir aber trotzdem nur einen schönen Weg durch die Stadt eingezeichnet.
Später bin ich dann zurück zum Hostel und habe geschmollt. Irgendwie war das hier doch total das Kaff, die einzige Tante im Hostel wollte nichts mit mir zu tun haben und ich war allein. Ne ganz schöne Menge Frust. In Sydney war immer jemand, mit dem man was machen konnte. Dann hab ich mir überlegt, dass wenn ich nichts mit jemanden machen konnte, ich halt alleine was machen musste und ich nahm mir eine Strasse hoch zu den Bergen vor, die ich so lange gehen wollte, bis ich nicht mehr so gefrustet war. Gesagt, getan… Es war zwar ein ziemlich langer Marsch, aber ich bin schliesslich auf einem netten Aussichtspunkt gelandet, wo ich mir die tolle Landschaft ansehen konnte. Mittlerweile war es auch schon etwas später und ich bin zurück in die Stadt und gepflegt bei McDonalds zu essen. Danach wieder zurück zum Hostel, wo mittlerweile auch andere Leute angekommen waren - zum Glück.
Später kam noch ein Deutscher, mit dem ich etwas mehr anfangen konnte, und der auch noch was unternehmen wollte. So sind wir an dem Abend noch in eine Kneipe gegangen sind, wo es Bier und etwas Livemusik gab. Das war sehr nett noch.
Heute morgen haben wir noch etwas länger geschlafen, sind dann einkaufen und später in nem Internetcafe frühstücken. Da sind wir jetzt immer noch.
Ich werde nächste Woche dann den Kurs machen und mit Internet sieht es etwas mau aus, aber ich halte Euch auf dem Laufenden. Über Mails oder Anrufe freue ich mich aber weiterhin. Die nächste Möglichkeit ins Internet zu kommen, wird wahrscheinlich dann erst am nächsten Wochenende sein. Bis denne!

=== 25.09.2004, 16:44 - Jackeroo-Kurs und mehr

Nachdem wir uns am Montag, den 13. fertig gemacht haben, um zum Jackeroo-Kurs zu kommen, kamen auch bald drei Geländewagen an, aus denen drei Leute ausgestiegen sind. Einer sah aus, wie ein “echter” Cowboy, Steve, der Mann von Jillian, die diesen Kurs leitet, Jim, ein älterer Aussie, der schon ein paar Kurse von Jillian besucht hat, und Simon, ein etwas jüngerer Kerl, der genau wie Jim schon an Kursen von Jillian teilgenommen hat.
Nach einigen Einkäufen, ging es dann los in die Pampa. Das Land hier ist wirklich toll! Es ist ein sehr trockenes Land, so dass zumindest die toten Bäume hier supertrocken sind und ein super Brennholz abgeben. Wie auch schon in Sydney gibt es hier alle möglichen bunten Vögel und Tierchen. Besonders hervorheben möchte ich hier die netten kleinen Kriechtiere. Da meine Unterkunft ja lediglich ein Zelt ist, das noch nicht mal “dicht” ist, hatte ich schon diverse Begegnungen. Hier gibt es auch diese grossen Spinnen, die es auch in Deutschland gibt, die sich manchmal auf der Toilette breit machen. Ich meine diese kleinen schwarzen, so 3cm Durchmesser. Es gab mal eine Zeit, als ich vor diesen Viechern sehr grossen Respekt hatte. Ich kann nur sagen: von diesen Spinnen bin ich geheilt. Hier gibt es erheblich größere und vor allem erheblich giftigere.
Anfangs habe ich das Zelt noch nicht nach solchen Tierchen abgesucht, aber das hat sich schlagartig geändert, als ich eines Abends in meinen Schlafsack stieg. Als ich halb drin war, kam mir nämlich ein ￼Huntsman, das ist eine etwa Handteller-grosse, behaarte, aber ungiftige Spinne entgegen; und zwar lief sie oben auf meinem Schlafsack und direkt auf mein Gesicht zu. Wow, really shocking! Aber was macht man mit so einem riesen Viech?! Ich hab also erst mal mit meiner Taschenlampe so 5 Minuten die Spinne angeleuchtet, um zu sehen was passiert und um zu überlegen, was ich denn machen will. Nach einiger Zeit kam ich auf die geniale Idee, die Spinne einfach mit meinem Sydney-Reiseführer zur Seite zu schnippen. Gesagt, getan… Ich hab sie also geschnippt… äh, aber wo war sie jetzt?? Ich kam mir vor, wie ein Huhn bei Chicken-Run (uaaaa!), hab sie gesucht und schliesslich gefunden. Mit einem beherztem schlag auf das fette Tierchen habe ich sie erst mal kampfunfähig gemacht. Als ich aber vorsichtig pustete, hat sie sich immer noch geregt, halt also nur so getan, als wenn sie tot wäre. Der finale Todesschlag hat ihr aber endgültig den Rest gegeben… und einen grossen Schleimfleck hinterlassen… das dazu.
Eine weitere Story: wenn man nach Australien geht, wird man ja immer vor diesen besonders giftigen Spinnen, den ￼Redbacks gewarnt. Die sind schwarz, mit einem dicken roten Fleck hinten drauf. Ich hatte bis dato so eine Spinne (zum Glück) noch nicht gesehen. Aber als wir eines Tages etwas Holz an Jillians Haus hervorholten, sah ich plötzlich eine Spinne, die in etwa so aussah. Ich hab Jillian also gefragt, ob das denn ein Redback wäre. Und sie meinte nur, “Ja, das ist ein Redback… Du hast doch Handschuhe an, mach sie mal platt…” Ich war etwas konstatiert, da man ja überall hört, dass dies die giftigsten Spinnen Australiens seien. Als ich nach einiger Zeit immer noch nichts gemacht habe, hat das dann Jillian für mich erledigt, indem sie meine Hand nahm und draufgehauen hat. Uiuiui, raue Sitten hier. Ich war etwas perplex und Jillian hat nur gelacht. Sie meinte nur “wieder eine weniger&quot;.
Aber eigentlich wollte ich ja nicht nur von Spinnen erzählen, sondern auch von dem ganzen Rest; ich hoffe, ich schaff das alles noch in 25 Minuten. Dann macht nämlich das Cafe hier zu.
Also: wir sind also bei Jillian angekommen und bekamen zuerst Zelte, dann Pferde entsprechend den Kenntnissen zugewiesen. Später hat sie uns gezeigt, wie das mit dem Satteln und auftrensen geht und es gab ein paar Vorführungen von Jim und Simon zum Thema Natural Horsemanship, a la Monty Roberts.
Noch am selben Tag haben wir einen Ausritt durch die Weideländereien und Wälder von Jillian und Steve gemacht. Wow, das Gelände ist schon recht unübersichtlich und supergebirgig, fast wie in Norwegen. Und die Pferde waren supertrittsicher. Wir sind da durch Schotter, über grosse Felsen geritten und steile Hänge auf und ab; wirklich super und abends gab es immer gutes Essen und immer ein Lagerfeuer. Die beiden Staffs aus Sydney waren auch supernett.
Später haben wir während des Kurses noch Kälber getrieben, so richtig nach Cowboy-Manier, wie man sich das vorstellt; da konnten die Pferde zeigen, was sie drauf hatten. Einige Leute haben von hinten getrieben und andere haben an der Seite aufgepasst, dass die Kälber auch in die richtige Richtung gegangen sind. Und wenn mal ein Kalb “ausgeschert” ist, musste man teilweise im Trab oder Galopp hinterher; das macht vielleicht Spass. Und das tolle ist, das das alles nicht nur zur “Show” ist, sondern, dass die Arbeit wirklich erledigt werden muss.
Ein weiterer Knaller sind die Hunde, die Jillian hat: Kaktus und Alby. Kaktus ist ein Collie/Dingo-Mischling, der aber eher wie ein Dingo aussieht. Die Beiden laufen immer die ewig langen Strecken, die wir teilweise am Tag zurücklegen, mit und teilweise sogar noch weiter; und mit was für einem Tempo, cool.
Wenn Jillian wollte, dass sie eine Kuh zurückholen, konnte sie die beiden so dirigieren, wie sie es haben wollte. Und das hat wirklich super geklappt. Und mit welchem Enthusiasmus die beiden das gemacht haben, und mit welcher Ausdauer, echt toll.
Ansonsten haben wir noch fencing gemacht, also Zäune repariert oder aufgestellt, Holz auf den Weideflächen zusammengesucht und verbrannt, einige Stunden in Natural Horsemanship genossen und gestaunt; das in aller Kürze. Ich muss hier bald mal Schluss machen, da die den Laden hier bald schliessen wollen, aber ich werde in nächster Zeit wohl bestimmt noch mal berichten.
Wenn ihr mich erreichen wollt, könnt ihr das am besten einfach machen, indem ihr bei Jillian anruft, und zwar am besten zwischen 12.30 und 13.30 deutscher Zeit unter der Telefonnummer +61267694385. Dort wird sich Jillian oder Steve melden und Euch bitten, nochmal anzurufen, damit wir dran gehen können. Die Nummer ruft aber bitte nur noch bis Donnerstag, den 30.09. an, da ich danach woanders hin gehe. Was ich genau machen werde, weiss ich nicht, aber wie es aussieht, werde ich nur noch zwei Wochen mit Steph herumreisen und dann auch schon zurückkommen, also etwa Mitte Oktober.
Ich würde mich echt über ein paar e-Mails freuen. Ich werde mich auch sicher mit einer netten Postkarte revanchieren. Hab grad n ganzen Batzen gekauft. Bis zum nächsten Bericht, Marc.

=== 03.10.2004, 19:37 - Wieder in Sydney

Nach drei Wochen “Verzicht” und Abwesenheit bin ich jetzt wieder in der Metropole Sydney. Doch vorher wollte ich noch etwas zu dem Kurs usw. schreiben; jetzt habe ich ja Zeit und die Möglichkeit, das Internet zu Nutzen, dank Stephs Arbeitgeber, dem “Australien Centre for Field Robotics". Hier sitze ich nämlich jetzt und erledige die ganzen Dinge, zu denen ich bei Leconfield nicht gekommen bin…
Doch fangen wir vorne an: nachdem der Jackeroo-Kurs zu Ende war, hatten wir eine Woche “frei", zumindest “Kursfrei&quot;, d.h. wir hatten andere Aufgaben, sind ausgeritten, haben teilweise unter Anleitung mit den Pferden gearbeitet, haben etwas Fencing gemacht (also Zäune aufgebaut bzw. repariert) oder andere Arbeiten erledigt. Soweit, so gut. Anfangs war ich auch noch recht zufrieden, weil mir die Arbeit - sei es mit oder ohne Pferd - immer gut gefallen hat.
Aber das grosse Problem an diesen Wochen “off” war, dass wir tagsüber zwar gut zu tun hatten, es aber abends schon gegen 18h dunkel wurde und wir also ab dieser Uhrzeit nichts mehr machen konnten ausser uns unterhalten, am Lagerfeuer sitzen oder einfach ins Bett gehen. Hinzu kommt, dass nur ich und Elisabeth an dem Haus waren, ansonsten ist man halt in der Pampa. Das führte bei mir dazu, dass ich mich mit der Zeit recht einsam gefühlt habe; naja, so ganz weit hergeholt war das ja auch nicht. Schliesslich war ja auch weit und breit niemand. Mir war nicht bewusst, dass die Jackeroo-Kurse nur alle zwei Wochen stattfinden und auch, dass man in dieser Zeit abends nichts mit anderen Leuten machen kann. Ferner gab es kein Radio, Telefon, Mobilfunknetz, geschweige denn Internet. Das fand ich halt ziemlich blöd. Daher habe ich mich entschlossen, doch nicht mehr so lange bei Jillian zu arbeiten und vorzeitig zurück zu fliegen.
Ich könnte mir natürlich jetzt noch einen neuen Job suchen oder andere Sachen machen. Ich bin aber mit meiner Entscheidung, noch 1,5 Wochen in Australien zu bleiben und dann zurück zu kommen, endlich einen Job anzufangen, sicherlich auch Judith wieder zu sehen (wie auch alle anderen) und erst mal einen “geregelten” Arbeitstag zu haben, sehr zufrieden. Ausserdem bin ich dann ja auch schon 1 1/2 Monate in Australien gewesen; war ja nicht nur ein paar Tage da und hatte tolle Erlebnisse und werde sicherlich in der verbleibenden Zeit noch einige tolle Erlebnisse haben.
Mein Rückflug steht schon fest: ich werde am Mittwoch, den 13. Oktober von Sydney nach Dubai und dann direkt nach Düsseldorf weiterfliegen, wo ich am 14. Oktober um 13.25h mit den Emirates ankommen werde; das nur soweit dazu.
Aber ich wollte noch etwas zu der letzten Woche bei Jillian und Steve schreiben: am Montag fing ja wieder ein Kurs an. Dabei handelte es sich um “Mountaincattle” (http://www.mountaincattle.com.au[http://www.mountaincattle.com.au]) und nicht um den Jackeroo-Kurs (http://www.leconfieldridenatural.com)[http://www.leconfieldridenatural.com)]. Dieser Kurs ist etwas teurer als der Jackeroo-Kurs, man muss allerdings auch nicht so viel Arbeiten. Während wir bei dem Jackeroo-Kurs an zwei Tagen auch Zäune repariert haben und Holz gesammelt und verbrannt haben, sind wir bei dem Mountaincattle ausgeritten.
Am Montag waren wir also alle gespannt, was für Leute kommen würden und wie sie so drauf sind. Von Jillian haben wir erfahren, dass es sich wohl nur um Australier handelt, bis auf eine Dänin, die aber nicht erschienen ist. Stattdessen hatten wir eine Holländerin im Kurs. Aber der Reihe nach: schon gegen 9h kam Ken an, ein Mann in den Vierzigern, der einen höllischen Aussie-Akzent hatte und seit vier Monaten erst aus der Army ausgetreten ist, nach 24 Jahren. Also jemand, der anpacken konnte, wie sich nachher beim Calf-Wrestling herausstellte… Leider habe ich mich mit Ihm nie so richtig unterhalten können; ich hab ihn einfach nicht verstanden Es war mir etwas zu peinlich, nach wirklich _jedem_ Satz nachzufragen, was er denn gesagt hat. Okay, soweit zu Ken.
Später kamen noch die anderen: Bryce, ein ich glaub 16jähriger Junge, der noch zur Schule ging und von seinen Eltern hergebracht wurde, besagte Holländerin, in den 40ern, die von ihrem australischen Bruder hergebracht wurde, eine australische Bankangestellte, Ende 20, die südlich von Sydney wohnt und Craig, ein netter Engländer, Ende 40, der mit seiner Familie nach Australien eingewandert ist. Er kam etwas später, weil er sich wohl ein bisschen verfahren hat. Wir haben ihn irgendwann auf der anderen Seite des Flusses mit seinem Cabrio durch den Staub zu Jillians Farm fahren sehen. Lustiger Typ…
Nachdem alle angekommen waren, verlief es eigentlich so, wie auch schon bei dem Jackeroo-Kurs: den Teilnehmern wurden Pferde zugeteilt und wir sind etwas ausgeritten.
An den weiteren Tagen, haben wir die meisten Sachen gemacht, die man auch bei dem Jackeroo-Kurs macht, nur halt nicht diese Arbeiten.
Lustig war noch ein Abend, an dem es draussen geregnet hat (eine echte Seltenheit in der Gegend, Jillian war total begeistert und hat sich gefreut… ), sind wir in die Scheune gegangen, wo wir uns gegenseitig Witze erzählt haben. Naja, mehr oder weniger… In erster Linie hat Craig welche erzählt. Er hat wohl mal für sechs Wochen als Comedian gearbeitet und kennt echt ne Menge Witze. Er braucht nur ein Stichwort und sofort kann er Dir dazu einen passenden Witz erzählen. Ich persönlich bin ja schon froh, wenn ich einen einzigen Witz behalte…
Was genau ausserdem noch passiert ist, kann ich ja dann mal erzählen, wenn ich wieder zu Hause bin. Ich habe wieder ein paar Fotos hochgeladen, die Ihr Euch wie immer unter http://marc-schumacher.smugmug.com/Holidays/29832[http://marc-schumacher.smugmug.com/Holidays/29832] ansehen könnt.
Jaa, ich wusste ja, dass ich Ende der Woche nach Sydney wollte und habe mich also bei den Leuten umgehört, wer denn dorthin zurück fahren würde. Im Gegensatz zum Jackeroo-Kurs sind nämlich die meisten mit Ihren Autos direkt nach Leconfield gekommen. Es stellte sich heraus, dass Craig wohl nach Sydney zurück wollte und mich auch mitnehmen wollte. Das fand ich natürlich total super, weil, wie ich ja schon geschrieben habe, Craig derjenige mit dem Cabrio war! Wir sind also nachdem ich meine Sachen bei Leconfield gepackt habe, am Freitag nachmittag gegen 17h Richtung Tamworth gefahren. Das war mit dem Gefährt von Craig wohl nicht so einfach: die Strasse nach Leconfield ist mehr oder weniger eine Schotterpiste mit tiefen Schlaglöchern, Flussüberquerungen und Wasserlöchern, so dass wir statt 20 Minuten mit einem 4WD mehr als die doppelte Zeit auf die Hauptstrasse brauchten. Von dort an ging es aber ganz fix. Wir sind dann in ein Motel gefahren, das Craig gebucht hat und zu dritt noch in einen Pub, wo wir, also Craig, Ken und ich, noch Kens Neffen getroffen haben. Man, das war hart. Ich war halt gewohnt gegen 21.30h schon ins Bett zu gehen und war zu der Zeit schon supermüde. Hinzu kam, dass wir in nem Pub natürlich noch das eine oder andere Bierchen getrunken haben, so dass ich noch müder war. Gegen 23.30h sind wir dann endlich gegangen. Ich weiss gar nicht mehr, wie ich den Weg noch zurück geschafft habe; ich war dermassen fertig. Nun gut, wir haben uns also das Zimmer geteilt, ich und Ken haben auf dem Boden geschlafen und Craig im Bett. Schliesslich hat er das Zimmer ja auch eigentlich für sich gebucht.
Am nächsten Morgen sind wir dann schon recht früh losgefahren. Sind kurz ins Drive-In von McDondalds gefahren, wo ich einen Muffin normalen, in Australien meist sehr grossen Muffin wollte, aber dummerweise einen englischen Muffin bestellt habe. Der Muffin war nichts anderes als ein Burgerbrötchen mit Butter! Echt ein Scherz, egal. Wir mussten noch Ken, der mit seinem Wagen schon vorgefahren war, seine vergessenen Stiefel vorbeibringen und sind dann über die Landstrasse gebrettert.
Mann war das geil! Der Wagen von Craig war nicht nur ein einfaches Cabrio, sondern hatte auch den einen oder anderen PS unter der Haube: knapp 400PS bei 4,6l Hubraum, von 0 auf 100 in 4,6 Sekunden. Der ging ganz schön ab! War echt ein tolles Gefühl! Ich kam mir ein bisschen vor wie bei einigen Szenen von Rainman. Dann haben wir das Radio angemacht und es lief auch noch “Beautiful Day” von U2, da konnte einfach nichts mehr schief gehen…
Später sind wir noch zu Craigs Haus gefahren, wo wir noch ein Süppchen und Sandwich gegessen haben. Das Haus war auch superschön in einem Vorort von Sydney gelegen, mit Blick auf die Skyline, palmenumrahmt.
Netterweise hat er mich dann auch noch zur Uni gefahren, wo ich Steph wiedergetroffen habe. Das weitere was hier passiert ist, ist nicht weiter erwähnenswert.
Ganz interessant ist aber vielleicht zu erfahren was wir vor haben. Wir wollen nämlich am kommenden Dienstag nach Brisbane fliegen, von wo wir auf die Fraser Islands fahren, die größte Sandinsel der Welt, über 100 km lang. Dort ist es dann noch ein bisschen wärmer, momentan 28 Grad, in Sydney 23. Weitere Infos über die Insel gibt es unter http://www.fraserisland.net[http://www.fraserisland.net] . Das ist also dann meine letzte Woche hier in Australien. Ich schätze mal, das das noch mal ein grosses Highlight sein wird. Ich schätze mal, dass ich von dort aus dann noch mal einen Bericht schreiben werde.
Wenn noch jemand etwas aus Australien haben will, so sollte er es möglichst bald tun. Ich werde morgen voraussichtlich einkaufen gehen und ein Paket nach Deutschland schicken. Ich habe nur noch am übernächsten Dienstag kurz Zeit einkaufen zu gehen, hoffe also, dass Ihr mir schnell schreibt, was ihr haben wollt; keine Skrupel, nur schnell . Ich habe leider die Liste verloren mit den Sachen, die ich den einzelnen Leuten mitbringen wollte (Stromausfall im PDA), daher schreibt mir doch bitte noch mal, was das war. Ich weiss nur noch von dem Kängurufell für Alex. BTW: War das ernst gemeint? Kosten hier etwa 40AU$.
Also: schreibt mir, auch wenn ihr es nicht bis morgen schafft. Ich versuche mein bestes etwas zu besorgen. Wir haben einen tollen Markt hier in Sydney, wo man so allerlei zu günstigen Preisen herbekommen kann.
Bis zum nächsten Bericht,
Marc.

=== 08.10.2004, 19:36 - Fraser Island

Nachdem ich einige Tage zusammen mit Steph in Sydney verbracht habe, sind wir schliesslich am Dienstag Richtung Fraser Island aufgebrochen. Wir sind zuerst mit einem Quantas-Flug nach Brisbane geflogen, von wo wir dann direkt nach Hervey Bay aufgebrochen sind. Hervey Bay liegt auf dem Festland, direkt in der Nähe von Fraser Island. Auf Fraser Island selbst gibt es nur recht teure Hotels, so dass wir uns entschieden haben, in dem YHA in Hervey Bay zu bleiben. Dort nach etwa 5h Fahrt angekommen, sind wir netterweise - wie das so in Australien der Fall ist - von einem Bus des Youth Hostels zu selbigen gebracht worden. Dort angekommen haben wir direkt Kontakt zu unseren Zimmerkollegen aufgenommen: einem Franzosen aus Bordeaux, der grad sowas wie eine Weltreise macht und zur Zeit halt in Australien ist und einem Brasilianer, der eine etwas kürzere Tour durch Australien macht. Das lustige war, dass beide genau die Tour gebucht haben, die Steph und ich auch machen wollten und zwar eine gefürte 4WD-Tour durch Fraser Island. Kurzer Hand haben wir uns also entschlossen, genau auch diese Tour zu buchen und auch mit den Beiden an dieser Teilzunehmen. Das Problem war nur, dass die Tour schon am nächsten Morgen gegen 8h losgehen sollte. Wir müssen also noch vorher buchen. Ich bin also in aller Frühe gegen 6.15h aufgestanden, hab in aller Ruhe geduscht und bin dann zur Rezeption getarpert. Dort angekommen hat mir die nette Dame gesagt, dass das Büro der Organisation erst um 7.30h aufmacht und wir es dann noch mal versuchen sollten. Ich hab mich also aufgemacht und bin erst mal zu nem Shop, in dem ich Duschgel gekauft habe. Steph hatte vergessen, seins mitzunehmen und mich gefragt, ob er denn etwas von mir haben könnte. Großzügig wie ich bin, hab ich ihm natürlich sofort gesagt, dass das kein Problem war; war es aber doch. Als ich nämlich morgens duschen wollte, habe ich festgestellt, dass ich selbst meins _auch_ vergessen hab. Typisch… Naja, deswegen habe ich es halt an dem Morgen noch geholt. Soweit dazu. Wieder in der Rezeption angekommen, bin hat die nette Dame direkt bei der 4WD-Firma angerufen und was soll ich sagen: es hat problemlos geklappt, so dass wir eine halbe Stunde später bereits unsere Tour antreten konnten: dass nenn ich Glück, obwohl uns das in Australien auch schon öfter passiert ist.
Um 8h sind wir also von einem Bus der Kingfisher Ranger abgeholt und zur Fähre gebracht worden. Nach kurzer Wartezeit kam diese auch an und wir sind zu Fraser Island geschippert. Ja, Fraser Island, die größte Sandinsel der Welt, aber trotzdem ziemlich grün und bewaldet. Nachdem wir ausgestiegen sind und einige Infos bzgl. der dort lebenden Dingos erhalten haben, sind wir in einen Bus gestiegen. Ich habe erst gedacht, dass der uns zu irgendwelchen Jeeps oder so fahren würde, aber dies war genau der Bus, mit dem wir während unserer drei Tage Aufenthalt dort herumgefahren wurden. Das ging auch prima! In der Nähe der Fähre gibt es noch asphaltierte Wege, aber sobald man etwas aus dem Gebiet heraus will, muss man zwingendermaßen ein 4WD benutzen (an dem ersten Sandweg, den man befährt steht auch direkt ein Schild “Engage 4WD&quot;. Ach so, für alle, die es nicht wissen: 4WD bedeutet Four Wheel Drive, also Allradantrieb. Auf Fraser Island sieht man ne Menge solcher Fahrzeuge, die man dort anmieten kann. Leider gibt sind auch damit einige unerfahrene Vorstadtrowdies unterwegs, die mit Vollgas den Highway runterfahren, ohne zu wissen, was für Gefahren in Form von Sandhügeln dort lauern und sich dann überschlagen und schwer verletzen. Dazu muss man wissen, der ein offizieller australischer Highway auf Fraser Island existiert: der Strand, der vollkommen unasphaltiert ist. Nun ja, zum Glück haben wir solche Leute auf unseren Trips nicht gesehen. Aber zurück zu unserer Tour: am Anfang der “Sandstrasse” befindet sich so eine Art Testparcours, auf dem man mal erleben kann, was einen erwartet, was die Sandstrassen betrifft. Das war wirklich wie eine Achterbahnfahrt, als unser Ranger mal richtig losgelegt hat. Der Bus war zwar gut gefedert, aber wenn man regelmäßig Höhen von ca. 30cm überwinden muss, dann wird man schon super durchgeschüttelt. Aber total lustig! Teilweise ist man echt mehrere cm aus dem Sitz gehoben worden Und am Anfang haben wir uns alle nur so angegrinst; später war das Routine.
Wir haben eine Menge gesehen: superschöne Süßwasserseen im Landesinneren (den Strand sollte man besser nicht zum baden nutzen, da es dort wohl eine Menge Haie und anderer Unannehmlichkeiten gibt), den “Urwald” mit einem kleinen Bach, den man, total untypisch - aufgrund der fehlenden Steine - überhaupt nicht gehört hat. Zwischendurch gab es immer wieder sehr interessante Erklärungen von unserem Ranger. Abends waren wir in festen Unterkünften untergebracht, mit heissen Duschen und sehr nett aufgemacht. Ferner gab es die Dingo-Bar, wo es Musik, Essen und Trinken gab, sowie einige Animateure, die uns zu “Trivial” genötigt haben (viele kennen wahrscheinlich Trivial-Pursuit; das ist halt so ähnlich). Später kamen noch so einige Trinkspielchen dazu, was dazu geführt hat, dass wir alle ziemlich abgefüllt waren, als wir früher oder später ins Bett gingen. Am nächsten Tag ging es dann endlich an den Strand an der Ostküste. Wir mussten also durch den (Ur-)Wald zum Strand fahren, der zum Glück etwas schlechter mit Sandhügeln ausgestattet war (Kommentar des Rangers zur Warnung: “Bump”). Dort hatten wir u.a. auch die Möglichkeit, in einem der Flugzeuge, die auch auf dem Strandhighway starteten, mitzufliegen, was ich u.a. auch gemacht habe. Naja, der Flug war zwar etwas kurz, aber doch ganz lustig die Insel mal von oben zu sehen. Später sind wir noch zu dem Mahena (?) Schiffswrack gefahren, das direkt am Strand lag. Das ist so ein Wrack, dass in vielen Broschüren und Reiseführern abgebildet ist; kennt ihr bestimmt! Naja, Fotos folgen…
Dann ging es noch zu einem Aussichtspunkt, wo wir ein paar Wale, Delphine und Haie bewundern können sollten, was aber nur teilweise auch so war. Aber Wale haben wir eine Menge gesehen.
Der letzte Tag war dann eher relaxing und wir sind grad wieder hier mit der Fähre in Harvey Bay gelandet.
Morgen werden wir Whale-Watching machen, was wohl supertoll sein soll. Auch hier: Fotos folgen. Unseren Bus haben wir umgebucht, so dass wir Sonntag schon nach Brisbane fahren, weil in Harvey Bay ansonsten nicht so viel los ist. Am Dienstag geht dann der Flug nach Sydney und am Mittwoch bereits mein Flug heim. Mal schauen, ob ich es noch schaffe, Euch hier von dem Rest zu erzählen. Ansonsten dann Live- Face2Face…
Bis dahin,
Marc

=== 10.10.2004, 22:02 - Whale watching in Hervey Bay

Nachdem wir unsere Tour auf Fraser Island hinter uns gebracht haben, haben wir direkt die nächste Tour gebucht. Diesmal ging es Whale Watching in Hervey Bay. Bei unserem Aufenthalt auf Fraser Island haben wir ein nettes Paar aus Freiburg kennen gelernt, das genau dieses Whale Watching auch machen wollte. Da sie schon gebucht hatten, haben wir uns kurzerhand entschlossen, dieselbe Tour auch zu machen. Glücklicherweise klappt es hier ausserhalb der Saison super auch kurzfristig so Touren zu buchen.
Am nächsten Tag ging es also kurz nach 10h los. Wir wurden von einem Transferbus von unserem YHA abgeholt und auf die Fähre verfrachtet. Dabei handelte es sich um einen recht grossen Katamaran, der bestimmt 50 Personen aufnehmen konnte. Wir sind also losgefahren und es hat einige Zeit gedauert, bis wir den ersten Wal zu Gesicht bekamen; das war aber nicht so richtig spektakulär, weil er nur sehr weit von dem Schiff entfernt geblieben ist.
Einige Zeit später gab es aber noch andere Wale, die erheblich näher ran kamen und auch ein paar Sprünge gemacht haben oder zumindest ihre Schwanzflosse gezeigt haben. Sehr nett! Die Fotos werd ich noch einstellen. Die Tour endete relativ abrupt, als wir zurückfahren mussten, um pünktlich um 15h wieder am Hafen zu sein. Es war ziemlich interessant, diese Buckelwale mal von nahem zu sehen. Wie sich nachher herausstellte, ist dies wohl auch das am besten geeignete Gebiet weltweit, um so ein Schauspiel beobachten zu können.
Später wieder in Hervey Bay bin ich noch etwas spazieren gegangen und hab mir einen neuen Haarschnitt verpassen lassen; dann noch ein bisschen gelesen und ausgeruht, bis es am nächsten Tag zurück nach Brisbane ging. Dort angekommen, haben wir uns erst mal ein Hostel gesucht und das nächste zum Bahnhof genommen. In dem Zimmer hat es gestunken, wie in einer Pumahütte, aber gut.
Relativ kurz nachdem wir angekommen waren, haben wir auch direkt einen kleinen Spaziergang (wie er im Lonely Planet steht) unternommen, der sehr nett war. Danach ging es zu einem multi-kulti-Fest in einem Park, wo diverse Gruppen aus verschiedenen Kulturen Musik gemacht haben oder etwas von ihren Spezialitäten zubereitet haben. Das war eine ziemlich grosse und ganz interessante Sache. Morgen geht es dann Koalas streicheln…
Bis denne,
Marc