= Fahrtenbericht Interrail-Tour Skandinavien (Sommer 1996)

von Thomas Abel und Marc Schumacher
Dies ist unser komplettes Fahrtentagebuch. Die Dati über den Textabschnitten geben immer den Tag an, an dem der Abschnitt verfasst wurde. Die einzelnen Teile wurden entweder von mir (Schumi) oder von Tom geschrieben. Es könnte vom Schreibstil etwas holprig erscheinen. Außerdem ist der Text extrem lang relativ unübersichtlich gesetzt (wird sich noch ändern).

== Tag 1, So, 18.08.1996, 15.30h

Hallo, here we are!
Sind heute morgens in aller Herrgottsfrühe noch vor dem ersten Hahnenschrei sprich 6.00h also noch vor Sonnenaufgang, der jedoch alsbald folgte, mit Norbis Wohnmobil in Richtung Norden d.h. Fehmarn aufgebrochen.
Stopp in der Heide, genauer: Bispingen mit See! Ui, toll!!!
10.10h Speisung durch Lydies gutgemeinte Kniften.
Sitzen jetzt auf der Fähre von Puttgarden nach (schaun 'mer mal). Alte Dänin hat uns äußerst erfreut, mit seligem Grinsen die Alc-Tax-free-Karten abgenommen. Müssen also auf harte Drogen verzichten!
Die Fähr-Verbindung von Stockholm nach Finnland steht noch nicht fest! Ob oder wieviel wir noch draufzahlen müssen ist uns auch noch unklar! Aber irgendwie werden wir schon ankommen. Haben schließlich gerade Rosis Geburtstagskarte geschrieben, also müssen wir auch am 20.08.96 in Lahti ankommen.

== Tag 1, So, 18.08.1996, 19.20h

In der Fähre sind wir erst mal in den nächst besten Zug eingestiegen, und wir hatten Glück, es war der richtige! Nämlich der nach Kopenhaven…
Also um 15.05h losgefahren, kommen wir um kurz nach sechs etwas ausgeschlafener in Kopenhaven auch an.
Jetzt müssen wir sehen wie wir weiterkommen; auf dem Plan mit den Reiseverbindungen (aus Bochum) steht nämlich "weiter mit Bus". Hmm, klar, nur welcher?
Kurzerhand entschließen wir uns einfach mal an der Information zu fragen, wo wir auch bereitwillig Auskunft erhalten. (Ich habe zwar noch nie gehört wie jemand eine Zahl in Englisch und gleichzeitig in Deutsch ausgesprochen hat, aber man mag es kaum glauben: man kann es verstehen).
Aus Versehen haben wir auch noch das Interrail-Center im Bahnhof gefunden, das wir uns natürlich erst mal angesehen haben, u.a. um unsere Information von der Information (hä?) zu verifizieren (ich liebe Fremdworte!).
Netterweise gab uns die nette (junge) Frau auch Auskunft, nämlich, daß wir uns an der Information erkundigen sollten (grmbf), aber praktischer Weise hat sie uns auch genau (auf einem Stadtplan) gezeigt, wo wir hin müssen; das war, wie sich später herausstellte, gar nicht so schlecht.
Nachdem wir nämlich aufgegeben haben, den Busbahnhof zu finden, sind wir direkt zum Hafen gegangen.
Dort angekommen und noch ganz unsicher, ob wir überhaupt bei der richtigen Fähre angekommen sind, stellten wir uns einfach mal an der Schlange (nach kurzer Wartezeit und einigen Erkundigungen Toms) an.
Wir wunderten uns zwar, daß einige Leute ihr Geld zurückbekamen, haben aber trotzdem nicht ganz verstanden, wieso… Das hat uns dann die nette Dame am Schalter erklärt: die Fähre fällt nämlich aus… Wir sollen doch bitte die andere Fähre nach Malmö, 200m weiter benutzen… "Toll!", dachten wir uns, da wir dachten, wir würden unseren Anschluss verpassen… Naja, Glück gehabt. Wir hätten nämlich, wenn wir diese Fähre genommen hätten, 31/4h Aufenthalt in Malmö… dies reduziert sich jetzt auf "nur" 21/4h… Achja… Wucher! Jetzt wollen die hier auch noch mal 20 Muck haben… So, jetzt hab' ich auch genug geschrieben, sonst verpassen wir die Fähre um 20.00h auch noch…

== Tag 3, Di, 20.08.1996, 02.07h (finnischer Zeitrechnung)

Ja, die Fähre haben wir dann tatsächlich nicht verpaßt und sind nach einer dreiviertel Stunde auch in Malmö (Schweden) angekommen.
Von dort aus sind wir dann auch schnurstracks Richtung Bahnhof gelaufen, den wir auch prompt gefunden haben (war auch kein Problem, da der nur 2 min entfernt und in Sichtweite war). Um nochmal sicher zu gehen, daß auch ein Zug um 23.00 Uhr Richtung Stockholm fährt, haben wir es uns sicherheitshalber nochmal bestätigen lassen.
Und da es auch erst ungefähr halb neuen war und unsere Magen auch schon brummten, haben wir uns auf den Weg in die Stadt gemacht. Mit Hilfe des Reiseführers konnten wir auch schon einige Fressbuden ausfindig machen, die aber alle schon geschlossen waren, weil in Malmö die Bürgersteige anscheinend schon um 21 Uhr hochgeklappt werden.
Jetzt war guter Rat teuer… apropos teuer: da Essen auch etwas kostet, kam uns der Gedanke vielleicht mal ein paar schwedische Kronen abzuheben. Und weil es schon so spät war und wir nicht an das Geld von Toms Postsparbuch kommen konnten, fiel die Wahl auf meine ec-Karte. Nunja, daß die Karte schon in Dresden, wo ich ja vorher mit den Pfadfindern war, nicht ganz so funktionierte, führte dazu, daß wir erst nach viermaligen Automatenwechsel das gewünschte Ergebnis erzielten… Puh!
Da ja wohl alle Fressbuden in der City geschlossen waren, entschieden wir uns kurzer Hand die Bude im Hauptbahnhof aufzusuchen. Dort genehmigten wir uns dann auch unsere wohlverdiente große Portion Pommes mit Majo und danach ein Eis; denn Geld hatten wir jetzt ja ;-)
Später holten wir dann unser Gepäck aus dem Schließfach, wo wir es vorher gelagert hatten und stellten fest, daß die Angaben auf unserem Reiseverbindungsplan ganz richtig waren und man tatsächlich Reservierungspflicht hatte. Dumm gelaufen, denn in Bochum hatte man uns gesagt, man könne nicht reservieren.
Glücklicherweise gab es noch die andere Zugverbindung nach Stockholm, die zwar knapp zwei Stunden länger dauern sollte, aber was tut man schon dafür doch noch an diesem Tag dorthin zu gelangen…
Nach relativ kurzer Zeit (ca. 1h) kamen wir auch schon in Helsingborg an, wo wir umsteigen mußten; der Zug stand auch schon da. Und er stand auch noch länger… und zwar eine ganze Stunde bis der Zugfahrer ihm die Sporen gab.
Mehr oder minder gut geschlafen wurde ich von leichtem Gitarrengeklimper geweckt. Der Mann war mir schon als er am letzten Abend eingestiegen war aufgefallen und mir einen leichten Hauch seines doch ziemlich hochprozentigen Mundgeruchs entgegenwarf.
Nach ca. einer halben Stunde, als Tom dann auch wach war, stand er plötzlich mit Gitarre auf und fragte mich, ob ich auch spielen könne, was ich bejahte.
Nachdem unsere Nationalität geklärt war, drückte er mir die Klampfe in die Hand und meinte nur "Spielen Sie Wiegenlied…" Reichlich verdutzt sagte ich, daß ich das Lied gar nicht kenne, auch wenn es aus Deutschland kam und fragte ihn von wem das eigentlich ist (kurzer Einschub vom Autor: - was macht der Tom eigentlich mit seinem Mund? Drückt die Lippen zusammen und scheint zu kauen… Komisch! Naja, werd' ihn morgen mal fragen, ob er Kohldampf hatte und vielleicht von Essen geträumt hatte…-)
"Äh, von Bach ist es nicht, hmm, von Schiller". Okay, das hätten wir geklärt. Trotzdem schien er immer noch darauf zu bestehen, daß ich das spiele; konnte ich aber nicht… Nach ca. 5 min hat er es dann auch eingesehen und fragte mich nach anderen deutschen Bands (?). Okay, dann hab' ich ihm ein Stück von BAP zum besten gegeben und damit war er dann auch zufrieden.
Endlich konnte ich ihm seine Gitarre wiedergeben, die er dann noch bis zum Ende der Fahrt eigentlich ziemlich gut spielte. Tom und ich waren uns einig: der Mann war ein bißchen komisch…
So gegen 8 Uhr (also mitten in der Nacht) sind wir im Hauptbahnhof von Stockholm eingefahren. Jetzt hatten wir erst mal bis Abends Aufenthalt und konnten uns nach einer ausgiebigen Dusche im Bahnhof, aufmachen und Stockholm besichtigen.
Und da wir wußten, daß wir hier 'eh noch mal hinkommen würden, haben wir uns auch keinen Streß gemacht. So kam es, daß Tom sich zu allererst mal eine neue Brille gekauft hat (auf die Alte hat sich ein Fahrgast in Dänemark ausgiebig breit gemacht, und so sah dann auch die Brille aus) und wir dann zum Königspalast gingen, den wir relativ kurz inspirierten. Beim Bäcker gab es jetzt sozusagen als Vorspeise, zwei trockene Brötchen; wir wollten nämlich erst mal vernünftig Frühstücken. Das "Material" dazu lieferte uns ein Supermarkt: 4 Milchbrötchen, 2 Roggenbrötchen, 2 Flaschen Cola, irgendwelche komischen Fleischballen und eine seltsame Käse-/Schinken-Mischung in der Tube.
Das ganze wurde dann gemütlich im Park verzehrt. Dann kam Tom auf die sehr gute Idee in das Viking-Museum zu gehen, wo man das Original des größten Wikingerschlachtschiffs, das 600m nach dem ersten Stapellauf schon sank, betrachten kann. Nur zu empfehlen!
Dann ging es wieder zurück zum Bahnhof, wo wir unsere Sachen abholten und per Bustransfer zur Fähre gefahren wurden. Ach ja, wir haben uns dafür entschieden, die Fähre direkt nach Helsinki zu nehmen, da diejenige nach Turku nicht umsonst gewesen wäre und die Überfahrt auch nur 20 Muck kosten sollten.
Also konnten wir dort angekommen um 18.00 Uhr losfahren. Eigentlich geht man ja davon aus, daß man, wenn man von Stockholm nach Helsinki fährt, ziemlich schnell auf die Ostsee stößt… Deswegen machte es uns etwas stutzig, als wir nach 2 Stunden immer noch keine Ostsee fanden… Am Ende war die Ostsee aber tatsächlich nicht ausgetrocknet…
Das Schiff ist einigermaßen nobel… Sauna, Bars, Disco, Cafés, Restaurants etc. etc.
Als der Großteil der Leute auf Deck unter Deck gegangen sind, konnte ich endlich mal versuchen, die extra mitgebrachte Tinwhistle zu spielen. Ich glaub' ich nerv den Tom auch später auf der Fahrt noch mal damit…. ;-)
Ein Problem hatten/haben wir nur: um Geld zu sparen haben wir keine Kabinen genommen; jetzt mußten wir also sehen, daß wir irgend etwas finden, wo man auf dem Schiff übernachten kann…. Gar nicht so einfach einen Ort zu finden, an dem es auch möglich ist zu schlafen (wenigstens ein bißchen). So ziemlich einer der einzigen Orte unter Deck hatte nämlich ein großes Manko: direkt an diesem Ort steht nämlich ein absolut nerviger Computerspieleautomat, der ungefähr jede Minute lautstark sein Jingle von sich geben muß &lt;NERV!&gt;. Zuerst konnte man ja noch darüber lachen, daß das immer und immer wieder kam, aber irgendwann hält man es einfach nicht mehr aus… Die Alternative war über Deck, also in der Kälte. Da ich (und später auch Tom) da einfach nicht einschlafen konnte und anfing mich anderweitig als mit schlafen zu beschäftigen (mit diesem Eintrag nämlich). Aber nach 1 1/2 Stunden wurde es auch Tom zu kalt und wir entschlossen uns, in den sauren Apfel zu beißen und zu versuchen, dieses beschissene Jingle zu ertragen. Bin mal gespannt, ob wir das schaffen… Ich für meinen Teil versuch jetzt auch mal ein Auge zu zu machen; es ist nämlich auch schon viertel vor drei (finnischer Zeitrechnung, also +1 Stunde) und wir legen heute um 9.00 Uhr in Helsinki an. Verdammt!!! Schon wieder dieses Jingle… Man neigt wirklich dazu, sich mal ausgiebig mit dem Ding auseinander zu setzen (mit dem Vorschlaghammer oder so…)… Bye…

== Tag 7, Sa, 24.08.1996, 21.35h

Wir sitzen jetzt an Deck der Silja "Symphony" und haben uns zum Bericht schreiben durchgerungen! Das alles ist bisher passiert:
Wir sind am Di, 20.08.1996 gegen 9.00 Uhr mit der Viking Linie "Isabella" nach stressiger Nacht in Helsinki eingelaufen. - Es hat nicht geschneit!!! Mit dem Bus ging es dann zum Central-Station. Unser Zug fuhr gegen 10.15 Uhr Richtung Lahti ab, wo wir gegen 12.00 Uhr ankamen. Rosi erwartete uns schon am Bahnsteig. Wir sangen "Zum Geburtstag viel Glück" und "Hoch soll sie leben". Nach der Geschenkübergabe wurden wir dann auch Richtung Enroos-Haus kutschiert; da wurden wir Seppo vorgestellt.
Nach dem Essen waren wir ein bißchen im Garten = Wald spazieren, während wir geklönt haben.
Gegen 19.00 Uhr (wieso schreib ich eigentlich immer: "gegen"?) sind wir wieder aufgewacht. Im Wohnzimmer warteten schon ein paar finnische Boys sowie Eijas Geburtstagstorte und diverse andere Sachen (wie Pizza) auf uns. Kurz vor 21.00 Uhr gings los nach Lahti-City. In einem Straßen-Pub haben wir dann auch Miia getroffen. Rom war dann auch eine Reise wert. "Roma" hieß die 1. Disco am Ort. Schumi hat sich mit Eija unterhalten, ich mit Miia, Rosi war mit Kristan dem Schweigsamen Fußballspieler beschäftigt. Das einzige Nicht-Dancefloor-Lied war auf Eijas Wunsch an den DJ nach einem "deutschen" Song Lemon Tree. Na gut! Trotzdem getanzt und Spaß gehabt!
Nach dem Frühstück so gegen 12.00 Uhr haben wir den Bus nach Lahti genommen. Infos eingeholt, Kuksa gesucht, Miia bei "Eis-Kiss" getroffen, Nahrungsmittel eingekauft, in der Bibliothek wir ein bißchen mit dem Internet-Computer gespielt, an der Bushaltestelle Mädchen aus Pöjhöläa wiedererkannt, zurückgefahren.
Farfalle mit Käse-Sahne-Schinkensauce gekocht und vertilgt. Davor hat Seppo uns aber noch Makkara aus Bochum serviert. Um ca. 19.00 Uhr kam sie uns holen -die wendige Miia- und nach einigen geflügelten Wendungen kam die Wende und wir fuhren los.
Am Steg am See, achnee!
War dat schön! Zu echter finnischer WDR 4-Folklore schoben die Finnen ihre Finninnen über die Planken -strange- doch auch wir wurden nicht verschont! Ach is dat nich romantisch - oder wat? Wat - Watt is' in der Steckdose.

== Tag 8, So, 25.08.1996, 10.45 Uhr

Sind jetzt im Zug von Stockholm nach Oslo.
Ich schreibe immer noch über Mittwoch, dem 21.08. Nachdem wir also den Tanzabend beendet hatten, haben wir uns noch eine schwedische Villa angeschaut, die heute ein Hotel ist. Danach hat Miia mit uns eine kleine Spritztour unternommen.
Wasserturm, Fernmeldemasten, Sprungschanze, McDoof usw. During sät teim wie luckt aut of sä windos änd wotscht sä skeis! It wos wärry fanny!
Donnerstag Morgen war Sightseen angesagt. Hoch ging es zur Sprungschanze - zuerst mit dem Sessellift und dann mit dem Aufzug nach ganz oben. Unten im Landebereich der großen Schanze gibt es eine Schwimmbad, das von einigen besucht wurde.
Unser nächstes Ziel war ein Park in dem versteckt große Steinskulpturen eines ortsansässigen Künstlers stehen. In Lahti gibt es das größte "Skigebiet" Finnlands. Mitten drin steht ein altes schwedisches Gehöft mit Hotel, Pubs und Souvenirläden, in denen typisch finnische Produkte verkauft werden. Hier hab' ich auch meinen neuen Elchschild-Pin her. Die Sommerrodelbahn war schon außer Betrieb. Die Sommerferien sind ja auch schon vorbei. Nachmittags haben wir uns das Haus angeguckt, in dem Rosi ihr Konfirmanden-Camp hatte. In Hollola wurden wir von einem Geschichtsstudent durch die älteste Kirche der Region geführt. Lahti war, bevor es den Eisenbahnanschluß bekam, ein kleiner Vorort von Hollola. Rosi zeigt e uns noch den See, an dem sie letzten Sommer mit ihren Freunden oft gewesen war. Zurück in der Karhunkatu haben wir mit ihrer Familie zusammen gegessen. danach wurde in Rosis Zimmer noch etwas gesungen. Abends waren wir dann bei Miia eingeladen. Wir haben Fotos angeschaut und uns unterhalten. Morgens, also Fr, 23.08.96 hat Seppo Rosi, Miia, Marc und mich zum Bahnhof gebracht. Kurz nach 11.00 Uhr kamen wir dann in Helsinki an. link:[McDoof] Zuerst haben wir Stockmann unseren Besuch abgestattet (wie konnte ich das vergessen: Laura (mit kurzen Haaren) ist mit uns für ein Stündchen über den Markt mitgegangen, dann mußte sie zur Klavierstunde.) um für Schumi eine Kuksa zun Helsinki an. link:[McDoof] Zuerst haben wir Stockmann unseren Besuch abgestattet (wie konnte ich das vergessen: Laura (mit kurzen Haaren) ist mit uns für ein Stündchen über den Markt mitgegangen, dann mußte sie zur Klavierstunde.) um für Schumi eine Kuksa zu kaufen, die wir dann im Hafen auf dem Markt gekauft hatten. Gegessen haben wir beim Pizza Hut. Um 15.00 Uhr ist Kalle zu uns gestoßen. Wir waren noch mal am Hafen, am Dom und in der Bibliothek. Dann wollte Kalle unbedingt nach "Alko", um Reserven für’s Wochenende in der Sommerhütte zu besorgen. Miia mußte schon wieder zurück nach Lahti zu einem Gruppenleiter-Camp der Kirche. Dann mußten wir mit Kalle das obligatorische Bier trinken. Um 18.00 Uhr ging dann Rosis Zu g nach Lahti und auch Kalle mußte sich verabschieden. Mit Brötchen, Mini-Frikadellen und Trinkjoghurt bewaffnet, haben wir uns dann in der untergehenden Sonne auf den Stufen des Doms niedergelassen. Um 20.30 Uhr haben wir dann LAura von ihrem Job bei Stockmann abgeholt. In einem Pub haben wir ein Glas Cider bzw. Kakao getrunken. Als wir dann unser Gepäck vom Bahnhof holen wollten, um uns lange Hosen anzuziehen, stand wir vor verschlossener Tür. - SUUUPER!-
Mit Lauras Hilfe konnten wir dann doch an unser Gepäck gelangen. Unser nächstes Ziel war "Zetor" eine Kneipe, die von einem Leningrad-Cowboy in "ländlichem, rustikalen Stil" designed wurde. Innen stehen Traktoren der alten finnischen Marke "Zetor" und diverse andere Landgeräte. ZU Live-Musik wurde auf gut finnisch Bier gekippt. Die Band spielte guten alten Rock`n`Roll und der Sänger erinnerte an Bruce Springsteen. Auf der Busfahrt nach Lauras Wohnung habe ich mich dann mit einem etwas angetrunkenen finnischen Naturburschen über die Vorzüge Finnlands unterhalten. Strange! Sa, 24.08.96 haben wir diverse Einkäufe verrichtet, die Uspenski-Kathedrale, das Nationalmuseum und die Felsenkirche besichtigt. Zum Mittag gab es Lachs von dem Crazy Fishman am Hafen, den wir wieder auf besagten Treppenstufen zu uns nahmen. Um 18.00 Uhr fuhr unsere Fähre Richtung Stockholm ab. Wir waren die letzten, die an Bord gingen.

== Tag 8, So, 25.08.96, 20.28 Uhr

Im Moment liest Tom noch 'was über die Flåm-Bahn vor, aber das macht ja nichts… ;-) Im Moment sind wir in dem Interrail-Center in Oslo, aber dazu später.
Die Fähre war eine gute Wahl! (Wieso haben wir das bloß nicht schon gemacht, als wir nach Finnland hin gefahren sind… 8-)). Naja, auf jeden Fall haben wir auf dieser Fähre eine Kabine gebucht… für 100 Mark (Finnmark); das entspricht etwas 33,- DM, von Helsinki nach Stockholm.
Auf jeden Fall haben Tom und ich nach einer kurzen Erkundungstour durch das Schiff (div. Shops, Restaurants und Bars) und einem ausgiebigen Duschgang ein bißchen gegessen (Tom einen Salat und ich natürlich Pizza) und heftig über Kunst insbesondere Popart diskutiert (ich fand auf dem ersten Blick das Popartbild in dem Restaurant ziemlich langweilig und habe es auch zum Ausdruck gebracht, was Tom nicht so stehen lassen konnte… dies führte zu einer längeren Diskussion (ca 1 1/2h).
Dann haben wir die Diskussion mehr oder weniger abgebrochen und sind an Deck gegangen, wo wir feststellten, daß dort sehr viele Stühle waren - hübsch aufgestapelt - nur leider zusammengeschlossen… &lt;ärger&gt;. Glücklicherweise haben wir dann doch noch eine Sitzgelegenheit gefunden, wo Tom damit begann dieses Buch weiter zu schreiben und ich Tom mal wieder mit meinem sehr unausgereiften Flötengedudel zu nerven.
Nach einiger Zeit und einigen mehr oder minder komischen Gestalten (fröhlich und normal), entschieden wir uns, unsere Kabine aufzusuchen und endlich mal wieder richtig und vernünftig zu pennen. Gesagt, getan…
Wir haben uns also hingelegt, das Licht ausgemacht und… das Licht wieder angemacht, was -rein helligkeitstechnisch- keinen großen Unterschied ergab, da zum einen ein an der Tür angebrachter Schiffsplan wie eine Glühbirne leuchtete und zum anderen eine ca. 5cm großer Spalt zwischen Eingangstür und Boden war; der Raum war quasi hell erleuchtet 8-|
Aber man is' ja flexibel und einfallsreich und so hab' ich kurzerhand das Bett über mir genommen und davorgepöppt und dann war Ruhe, bis am nächsten Morgen der lokale Schiffswecker ein paar sehr unsanfte Geräusche von sich gab und uns beide weckte (Zitat: "Wat is denn dat???").

== Tag 11, Mi, 28.08.1996, 19.52 Uhr

Ich denk' es ist mal wieder an der Zeit, etwas zu berichten… Wir sind im Moment im Interrailcenter in Oslo…
Ja, wo waren wir stehen geblieben… ach ja, wir waren gerade auf der Fähre aufgewacht; es war 7.30h, wir sind aber beide ganz gut aus den Betten gekommen.
Nach der obligatorischen Dusche haben wir, da die Zeit schon vorangeschritten war, an Deck gegangen, wo wir feststellten, daß wir ja noch einige finnische Münzen hatten…
Unter Deck haben wir uns dann an einer der reichlich vorhandenen Shops jeweils ein Eis und ich zusätzlich einen Elch geholt (nein! keinen echten, nur einen kleinen Holzanhänger).
In Stockholm wieder angekommen und den Zoll passiert sind wir auch prompt zum Bahnhof aufgebrochen um schnellst möglich den nächsten Zug nach Oslo zu erreichen. Da wir aber noch etwas Zeit hatten, gönnten wir uns ein paar belegte Brötchen plus Tafel Schokolade (Zitat: "Bei der Presse gibt es doch keine Brötchen?!") und genossen beides bei einer Folge Pippi-Langstrumpf über die Bahnhofs-Monitore.
Um 9.56h ging dann der Zug Richtung Oslo. Die Fahrt ging durch altbekanntes Territorium: einige Ortsnamen (Kil, Arvika) erinnerten uns doch an alte Pfadfinderzeiten in Värmland anno 1990. Nach dieser melancholischen Phase kamen wir auch bald an die schwedisch-norwegische Grenze an der sich sehr kraß die landschaftlichen Formen änderten (Tom: "naja!!!") (Schumi: "doch! wirklich!"). Aus der eher Tundra-ähnlichen mit Wald bewachsenen Landschaft wurde eine felsige, bergige und feuchte.
Ansonsten gibt es eigentlich nicht viel zu berichten; nur später stieg eine echte norwegische Familie, (fortsetzung von Tom folgt:) d.h. nur die Mutter mit ihren beiden Kindern. Der Vater wurde winkend am Bahnsteig zurückgelassen geguckt. - Zwischendurch sind wir immer widem bewölkt war und zu regnen begann, sind wir in ein Restaurant gegangen, in dem jedes Gericht 45Kr kostet. Ich: Lachs, Schumi: Steak.
Das hört sich toll an,war aber nur für den hohlen Zahn. Als wir dann durch den Park des Akerskus-Schlosses lustwandelten, find die Sonne wieder an zu scheinen (kurze Unterbrechung: Schumi wackelt mit den Ohren!!!). Dann sind wir noch ein bißchen im HAfen und der Innenstadt rumgelatscht und haben Postkarten gekauft. Gegen 23.00h ging es wieder los Richtung Bergen. Neben uns haben sich die bekloppten Bayern niedergelassen, von denen einer so aussah, wie der Sohn von Wolfgang Schäuble. Die waren mit ihren schlechten Witzen eigentlich nur Scheiße.
Dazu kam, daß wir unsere Sitze, die als einzige gegen die Fahrtrichtung waren, nicht in die Liegeposition stellen konnten. Obwohl wir im Gegensatz zu den Bayern wir vorgeschrieben reserviert hatten. Nur gab es unsere ursprünglich uns zugedachten Sitzplätze überhaupt nicht! NETT!!! So wurde die Nacht auf Montag zur Tortur. In Bergen angekommen, beschwerte ich dann auch noch ein Bayer mit Liegesitz über den mangelnden Komfort mit nur einem Sitz, grrr! In Bergen angekommen, wie gesagt, sind wir zuerst einmal zur Tourist-Info hin, waren dann auf dem Markt, wo Schumi sich seinen zweiten Elch später noch kaufen sollte. In einem Supermarkt haben wir uns dann fürs Frühstück ausgerüstet, welches wir dann am Fähranleger zu uns genommen haben (Alles nachdem wir beim CVJM nicht duschen durften!). Dieses Vorhaben verursachte eine Hitchcock-ähnliche Szene am Kai: Eine Vielzahl von Spatzen stürzte sich auf unsere Brotkrumen, so daß wir alsbald diverse Luftkämpfe der flatternden Gesellen zu unserer und aller Freude provozierten.
Unser Sightseeing-Ziel war das Aquarium von Bergen. Hier trafen wir neben alten Bekannten aus dem Biologieunterricht auch wieder unsere fröhlichen Bayern. So gegen 15.30h habe n wir uns dann Richtung Flåm vom Acker gemacht, da wir um ca. 18.00h dort ankommen wollten. Doch schon in Voss mußten wir unseren Zug verlassen, da die weltberühmte Flåm-Bahn ausgefallen war und wir mit dem Bus nach Flåm an die Spitze des Fjords gefahren wurden. Das war aber gar nicht schlecht. Auch vom Bus aus hatte man schöne Eindrücke der norwegischen Fjordlandschaft. In Flåm selber sind wir dann eigentlich sofort zum Campingplatz und Youthhostel gegangen, wo wir uns schon von Bergen aus telefonisch angekündigt hatten. Nach einigen Überlegungen haben wir uns dann doch für Betten und gegen unser Zelt entschieden. Weise Entscheidung, denn nachdem wir in unserer Hütte waren, fing es an zu schütten. Unsere Zimmergenossen waren alle älter als wir. Man merkt schon, daß die Ferien vorbei sind, und sich alles auf Winter einstellt. Überall ist recht wenig los und Jugendliche in unserem Alter sind rar. Die Jungs, ein Engländer, ein Spanier aus Madrid und ein Franzose waren aber ganz ok. Als der Regen aufgehört und wir unsere erste Portion Nudeln vertilgt hatten, machten wir in der untergehenden Sonne, von der nichts zu sehen war wegen der Berge ringsherum, einen Spaziergang bis es stockfinster wurde. Dabei haben wir dann tiefschürfende Männergespräche geführt. Am nächsten Morgen (also Dienstag) sind wir um 9.00h aus den Betten, um zu Duschen! Kurz vor halb 11 haben wir uns dann vom Acker gemacht, um einzukaufen und um dann mit der legendären Flåm-Bahn zu Tal zu rauschen. Die Fotos werden dazu genaueres zeigen.
In Myrdal stiegen wir dann um in den IC zurück nach Oslo. Die Landschaft um uns herum war toll, doch war die Stimmung eher gedrückt. Um unsere ganze Fahrt abzukürzen, entschieden wir uns Oslo Oslo sein zu lassen und von dort direkt nach Trondheim weiter zu fahren. Aber erst einmal in Oslo haben wir unsere Nachtzugreservierung wieder geändert und sind geblieben. Wir haben dann noch eine nette, Deutsch sprechende Französin kennengelernt:
"Ich schreibe nun ein bißchen, weil es wirklich schwer auf deutsch ist zu schreiben. Es war ganz lustig euch überall zu treffen und auch ein Reisetagebuch zu lesen. Es ist immer toll für mich deutschen zu treffen so ich war froh mit euch ein bißchen zu unterhalten. Vielen Spaß für den Rest deine Reise.
Elise.
P.S. Wenn ihr fahrt nach India oder Afrika, mußt ihr mich eine Postkarte schicken.
link:[Adresse von Elise]
Ja, genau diese meine ich! Wir haben sie öfters mal wieder getroffen.
Wir mußten ja irgendwo in Oslo übernachten. Das CVJM-Heim war geschlossen, die Jugendherberge sehr teuer. Da hat uns der Mensch im Interrail-Senter an Ingre Forus vermittelt. Zuerst haben wir uns gar nicht getraut dort zu klingeln. Wir waren doch tatsächlich richtig! Ingre hat einfach ein paar Räume seiner Jahrhundertwende-Wohnung zum Nachtquartier umgemodelt - Strange! Wer hat wohl da gewohnt? Elise! Wir haben uns dann einen Schlüssel geben lassen und sind dann losgezockelt. (Zitat: "Warum kommen wir immer ins Industriegebiet?!") Oslo bei Nacht: Schloßpark mit Trachtengruppe, Bahnhof -&gt; weil's Spaß macht und schmeckt (so weit zur gängigen Sexualmoral der NorwegerInnen). Industriegebiet, Hafen, Vollmond, Neustadt und zurück zu Ingre. Nacht! Heute: Mittwoch der 28.08.96 sind wir so gegen 9.00h aus den Federn sprich Penntüte gekommen. Auch unsere internationalen Zimmergenossen und Elise waren zu dieser Zeit munter. Das Bad war nur ein bißchen siffig - also clean by yourself oder so! Naja, ab durch den Schloßpark Richtung Bahnhof. An der Uni macht und schmeckt (so weit zur gängigen Sexualmoral der NorwegerInnen). Industriegebiet, Hafen, Vollmond, Neustadt und zurück zu Ingre. Nacht! Heute: Mittwoch der 28.08.96 sind wir so gegen 9.00h aus den Federn sprich Penntüte gekommen. Auch unsere internationalen Zimmergenossen und Elise waren zu dieser Zeit munter. Das Bad war nur ein bißchen siffig - also clean by yourself oder so! Naja, ab durch den Schloßpark Richtung Bahnhof. An der Uni macht und schmeckt (so weit zur gängigen Sexualmoral der NorwegerInnen). Industriegebiet, Hafen, Vollmond, Neustadt und zurück zu Ingre. Nacht! Heute: Mittwoch der 28.08.96 sind wir so gegen 9.00h aus den Federn sprich Penntüte gekommen. Auch unsere internationalen Zimmergenossen und Elise waren zu dieser Zeit munter. Das Bad war nur ein bißchen siffig - also clean by yourself oder so! Naja, ab durch den Schloßpark Richtung Bahnhof. An der Uni spielten sie (d.h. irgendwelche Studenten in schwarzen Roben und weißen Perücken) uns zünftige Blasmusik! Da gab's wohl 'was zu feiern. Im Interrail-Senter ließen wir unsere Klamotten einschließlich und besorgten uns was zu futtern aus dem Bahnhofssupermarkt. Nach besagtem Mahl bei dem uns eine Münchnerin unterhielt, indem Sie von den Lofoten schwärmte, haben wir einen Walk durch die Stadt gemacht und sind -welch Zufall - genau am Hafen ausgekommen. Dort haben wir die gemeinen Waschlappen getroffen, die sich zu unserem Leidwesen schon gewaschen hatten. Wenigstens hatten Sie noch so 'ne grüne Instant-Kothe mit sich - das war doch mal 'was! Aus Freude darüber haben wir dann echte Lappen-Handarbeit zum umhängen erstanden: Dieses Zeichen heißt soviel wie: "Lappenfreund, sei mir gegrüßt, wie Du dort so unsere grüne Kothe bewunderst. Also nimm hin dieses von Thor und Odin gesandte Zeichen zum persönlichen Sonderpreis von nur 40 norwegischen Königsgeschmeiden. Oh, Du Auserwählter!"
Mit so viel Glück in der Tasche konnten wir es nun auch wagen, die unbändige See zwischen Rathaus und Musemsinsel herauszufordern und bezwingen. Zu diesem Zwecke nahmen wir die Fähre um 14.25h bei sengender Sonne und stachen frohen Mutes in See.
Doch die - oder besser der - See war uns aufgrund der kürzlich erworbenen heiligen Glücksknochen (ja, genau die! Für nur läppische 40 NKr!) und vielleicht des nicht viel zu schlechten Wetters (den ganzen Tag schien schon bei strahlend blauem Himmel die Sonne) gut gesonnen und so erreichten wir unbeschadet und unverletzt die Museumsinsel.
Kaum angekommen sahen wir schon ein erstes Expeditionsschiff! Und das schreibe ich nicht nur einfach so, sondern voller Enthusiasmus und Freude, daß dieses Schiff nicht ein einfaches, schnödes Expeditionsschiff war, sondern es war das Schiff des bekannten, ja gar höchst, wenn nicht weltbekannten Friedjoff! Und ich spreche nicht von Friedjoff, dem Kindermadenwurm, der uns schon viele lustige, aber auch traurige Stunden bescherte, auch wenn die Szenen manchmal ein wenig überzogen waren und grotesk anmuteten (ich spiele auf die Szene an, in der Friedjoff mit seinen Rasierklingen-scharfen Reißzähnen die Darmwand eines herumtollenden Hundes perforierte), nein, dieser Friedjoff war nicht gemeint, sondern nur der langweilige Friedjoff Nansen, der, okay, den Norden und, ja, ich geb's ja zu, auch vielleicht den Südpol erforschte und auch erster am Nordpol war. DAS WAR ABER AUCH SCHON ALLES! (Verglichen mit Friedjoff, dem Kindermadenwurm ziemlich dünn, oder?).
Auf jeden Fall machten wir uns auf zum Kontiki (keine Anspielung auf das Sprichwort "Kommt Zeit, kommt Rat…&quot;)-Museum, wo u.a. eine Ausstellung über die RA I und II war, die, wie wir ja alle wissen, das erste Papyrusschiff unseres Jahrhunderts war, das es von Europa bis Südamerika schaffte.
Nach diesem Besuch ging es weiter mit dem obligatorischen, ja fast sprichwörtlichem Klotest, den wir mit bravour absolvierten…
Jetzt blieb nur noch eins zu tun: mit möglichst großen Umwegen eine direkte Verbindung vom Kon-Tiki- zum Wikinger-Museum zu schlagen (wie man weis, ist ja die kürzeste Verbindung zwischen zwei Punkten ein Sinuskurve mit maximaler Amplitude). Auch diese Prüfung legten wir mit Bravour ab (&lt;grr&gt;&lt;ärger&gt;).
Na, okay… In diesem Museum gab es drei mehr oder minder gut erhaltene Wikingerschiffe zu betrachten (oh, jetzt schalten die hier das Licht auf Sparflamme…) gab.
Als wir auch damit fertig waren, ging es zurück an dem Strand, der keiner war… Dort war nämlich nur die Anlegestelle von der Fähre, also entschlossen wir uns, diese auch, nach kurzem Imbiss, zu nehmen, doch dazu morgen, äh, heute mehr…

== Tag 12, Do, 29.08.96, 05.35h

Wir sitzen hier immer noch im Nachtzug nach Trondheim, und da wir eh nicht mehr schlafen (aus verschiedenen Gründen), will ich hier nochmals über die weiteren Geschehnisse berichten: wir sind also von der Museumsinsel wieder 'runter und mit der Fähre aufs Festland gekommen. Da der kleine Imbiss von vorher nicht reichte, sind wir auf eine Anhöhe am Schloß gegangen, um eine weitere Mahlzeit zu uns zu nehmen. Dort stellten wir erfreut fest, daß die Stadt wohl gerade neue Kunstwerke aufgestellt hatte. Außerdem wußten wir jetzt erst dem Kunstwerk zu würdigen, daß vorher dort schon stand, als wir dessen Schatten betrachteten, von dem man nie hätte schließen können, daß er von einer solchen Figur kam.
&lt;BILD&gt;
Außer dieser bewunderten wir natürlich auch die vielen anderen (neuen) Figuren, die größtenteils echt interessant waren. Danach haben wir uns noch das Rathaus von hinten angeguckt; war auch noch ganz interessant (nur diese seltsamen sozialistisch angehauchten Figuren…).
Obwohl es erst Nachmittag war, waren wir schon relativ müde, weswegen wir uns gemütlich auf den Weg zum Bahnhof machten.
Als wir am Nationaltheater vorbei waren, kamen wir an eine relativ große Menschenmenge vorbei. Und was tut man, wenn man eine gaffende Menschenmenge sieht? Richtig! Man stellt sich dazu und gafft mit!
Wir standen vor einem schmucken Restaurant und davor konnte man einige Kamera- und andere Leute, die sehr wichtig aussahen (Bodyguard, Aufnahmeleiter) sehen.
Es gab zwei interessante Gerätschaften, an denen die Kameras befestigt waren: zum einen hatten sie da einen ca. 8 Meter langen Schwenkarm, an dem man die Kamera mit einer Art Joystick steuern konnte. was der Kameramann auch ausgiebig testete - Einige vorbeifahrende Autofahrer mögen sich etwas beobachtet gefühlt haben - zum anderen war da ein Kameramann, der ohne Kamera aussah wie der Terminator. Damit konnte man extrem ruckelfreie Bilder machen, auch wenn man sich ruckartig bewegte.
Naja, nach einigen wichtig aussehenden Gästen und einigen sehr großen Autos, die am Eingang stoppten, entschieden wir uns, nach ca. einer 3/4h doch endlich zum Interrailcenter zu gehen und vielleicht später noch mal vorbeizukommen, wenn die Show beginnt.
(Es ist übrigens der 31.08.1996 und wir sitzen gerade im Zug von Stockholm nach Göteborg) Auf dem Weg zum Oslo-Interrail-Senter durften wir noch eine fähige Straßenmusikerin bestaunen. Im Interrail-Senter haben wir dann versucht dieses Buch auf den neueren Stand zu setzen. Und wen haben wir mal wieder getroffen? - Elise (!), die uns auch einige Zeilen in diesem Buch schrieb (siehe vorher)! Gegen 23.00h fuhr dann unser Nachtzug nach Trondheim ab. Sollten wir diesmal in Ruhe schlafen können? Naja - da gab es so ein kleines weißes etwas mit roter Schleife im Fell und stank auffallend nach Kotze. Wir überlegten uns diverse Möglichkeiten dieses Problem auf eine mehr oder weniger elegante Weise zu lösen. Am humansten war da noch der Teppichschaum, den wir auf diesem Wischmop aplizieren wollten! Trotzdem war diese Bahnfahrt nicht allzu schlecht, denn wir konnten live den Sonnenaufgang über der Hügellandschaft sowie den Mond und die Nebelschwaden bewundern. In Trondheim angekommen, haben wir uns erst einmal zum Interrailcenter des Studentenwerkes aufgemacht. - Schade! - Die Saison ist zu Ende, jetzt wohnen dort wieder die Studenten. Macht nichts! Zurück zum Bahnhof, aber diesmal mit dem Bus. Im Interrailcenter im Bahnhof, welches wie ausgestorben war, änderten wir erst einmal das Werbeplakat des Studentenwerkes, um weiteren Inter-Railern den Weg zu ersparen. Die Klamotten weggeschlossen, erstürmten wir das kristiansten Fort, von dem wir eine gute Aussicht über Stadt und Fjord hatten. Wieder unten angelangt ist Schumi erst einmal Mitglied mit Magnetkarte usw. der Bibliothek von Trondheim geworden, um den Internet-Computer benutzen zu können. Doch nach allem konnten wir dann doch keine e-mail verschicken. Eine weitere Möglichkeit hätte uns das Telefonmuseum eröffnet: hier konnte man nämlich für Nüsse und ein bißchen illegal das Demonstrations-Faxgerät benutzen. Doch genau an diesem Tag fand in dem dazu vorgesehenen Raum eine Tagung statt. So bekamen wir dann nur unsere kleine Privatführung durch einen Raum vollgestopft mit alten Telefonen und Schaltstellen aus der Region Trondheim.
Danach suchten wir das All-You-Can-Eat-Pizza-Restaurant auf, in dem es für 56 Kr. die besagt Mafiatorte als Speise gab. Das "Restaurant" war in einem düsteren Kellergewölbe untergebracht und wurde von einem glatzköpfigen Schwarzen betrieben, der uns dann eine ca. 50cm Ø-Pizza Salami/Hawaii kredenzte. Die ganze Atmosphäre hatte etwas Abenteuerliches.
Voll bis zur Oberkante Unterlippe diffundierten wir dann Richtung Nidaros-Domkirche. Hier fanden seit altersher die Krönungen der norwegischen Könige statt. War ziemlich düster der Kasten. Auf dem Weg zum Bahnhof machten wir dann noch diverse Umwege durch die Einkaufsstraßen. Um 15.49h nahmen wir dann den Zug Richtung Schweden. Der Zug brachte uns u.a. nach Hell!
Kurz vor der schwedisch-norwegischen Grenze mußten wir umsteigen und entschieden uns direkt und ohne Umweg nach Stockholm zu fahren. Hier trafen wir im Nachtzug einen verrückten ca. 65jährigen Ami, der über seine unzähligen Welt- und Auslandsreisen berichtete. Er hält den Rekord im Guinness-Buch, die meisten Bahnstrecken der Welt bereist zu haben. Am Freitag, 30.08.1996 kamen wir völlig übernächtigt in Stockholm an. Zuerst suchten wir unsere Jugendherberge auf dem Segelschiff "af Chapman" und duschten dort ne Stühle und man latschte praktisch nur über Grabplatten. Ziemlich gruftig dieses Ding.
Dazu haben noch etliche Adelige ihre Wappen dort anbringen lassen. Danach ging es unter das Parlaments-Gebäude ins Mittelaltermuseum in dem Ausgrabungen, Rekonstruktionen und Modelle zu bewundern waren. Ich fand's echt gut gemacht und ansprechend. Hier kauften wir uns auch mittelalterliche "Musik"-Instrumente Maultrommeln. Fürs Nationalmuseum hatten wir nur noch eine Stunde Zeit, in der wir uns diverse Bilder anschauten. Vor unserem Segelschiff haben wir dann gleich zwei Pakete Nudeln zubereitet und einige Passanten haben komisch auf unseren Benzinkocher geguckt. Geschmeckt hat es trotzdem! Der Abend sollte noch richtig interessant werden. Wir haben nämlich einen ca. 70jährigen schwedisch-stämmigen Amerikaner kennengelernt, der nach den Wurzeln seiner Familie gesucht hatte. Er hatte an der Uni Chicago Biologie und Ökologie unterrichtet. Wir führten lange Gespräche. Später ist dann wieder unser israelischer Kajütengenosse zu uns gestoßen, nachdem er die Synagoge besucht hatte. Er lud uns zum obligatorischen samstägigen Abendmahl ein (für Juden beginnt der Tag nach Sonnenuntergang). Auf meine Nachfrage erzählte uns der strenggläubige Student, der gebürtig aus Jerusalem stammt über die jüdischen Traditionen und Bräuche. So gegen 24.00h sind wir dann alle in unseren Kojen verschwunden. Heute morgen haben wir noch mal einen kleinen Stadtbummel unternommen, T-Shirts gekauft und etwas zum Essen. Seit 12.12h sitzen wir jetzt schon hier im Zug nach Göteborg und es ist 15.15h.

== Tag 15, So, 01.09.1996, 08.45h

Ich sitze hier gerade in der Jugendherberge in Göteburg; Tom wäscht sich gerade und ich hab` nichts zu tun…
`Mit etwas Verspätung sind wir gegen 16.30h in Göteborg Hauptbahnhof angekommen. Nach einiger Sucherei in selbigem, entschieden wir uns in der Stadt nach der obligatorischen Tourist-Information zu suchen.
An der ersten sind wir wohl vorbei gerannt und als wir an einer Karte, die anscheinend sehr nah an der nächsten war, nach derselben suchten, stellten wir fest, daß oben rechts ganz dick &lt;Bild Tourist Information&gt; stand. Toll!!!
Etwas verwirrt gingen wir zurück Richtung Bahnhof, um die erste Tourist-Information zu finden, als Tom (ich war eine paar Meter voraus) ein paar Deutsche fand (die findet man übrigens anscheinend immer und überall in Skandinavien), die bereitwillig Auskunft erteilten.
Sie sagten uns, daß die Karte wohl kaum die Tourist-Information sein konnte, aber etwa hundert Meter weiter eine Reiterstatue stand, an der auch eine Tourist-Information ist.
Schnell gefunden und eine Karte besorgt, wo 2 Jugendherbergen sein sollten, gingen wir auch schon los.
Mit der Orientierung gab es einige Probleme: Tom war der Ansicht, daß man sich nach den Straßennamen richten sollte, ich war eher der Ansicht, daß wir uns nach der Himmelsrichtung (also quasi nach der Sonne) richten sollten, weil man so flexibler ist… egal, auf jeden Fall konnte mich Tom überzeugen, doch nach Straßennamen zu gehen, was wir (Tom: "nein, es muß 'ich' heißen) an der nächsten Kreuzung ausprobierten und prompt in die falsche Richtung gingen. Nachdem wir das bemerkt hatten, ging es aber ziemlich straight in die richtige Richtung.
Der Weg schien nie zu enden und wir kamen schon auf den Gedanken -wie absurd- öffentliche Verkehrsmittel zu benutzen. Kernig wie wir sind, haben wir das natürlich nicht getan und kamen ziemlich erschöpft an der Jugendherberge an. Sah echt nobel aus (fast wie ein Hotel), nur hätte man wohl vorher (wie das Ding aussah, Wochen vorher) reservieren müssen.
Glücklicherweise kannte die Frau am Schalter noch eine andere Jugendherberge in der Nachbarschaft, die wir alsbald aufsuchten.
Jetzt völlig am Ende, erzählte uns die Heimleiterin ungefähr eine halbe Stunde etwas über die Jugendherbergen Göteborg, und den ganzen Rest, ohne daß wir danach gefragt haben…
Schließlich konnten wir doch hoch ins Zimmer gehen und beschlossen zuerst Geld abzuholen und dann was zu essen…
Der erste Geldautomat hatte zwar zu, aber glücklicherweise hatten wir noch genug Geld, um in einer Pizzaria zu speisen… Gar nicht schlecht: zu etwa gleichen Preisen wie in Deutschland (!) - außer vielleicht Cola-Preisen bekamen wir zusätzlich einen Salat und eine große Pizza.
Vollgefressen machten wir uns auf in die Stadt; aber erst noch zum Hafen. Bei einem etwas heftigerem Schauer mußten wir uns erst mal unterstellen.
Danach gings ab in die Innenstadt, wo sich anscheinend alle Jugendlichen in die Kinos verdrückt haben (standen zumindest die meisten davor und waren nachher weg).
Zum Glück haben wir aber dann noch einen gut gefüllten Irish-Pub gefunden, wo wir etwas tranken und später zurück zur Jugendherberge gingen, wo wir nach Codeeingabe (die Jugendherberge hatte ein etwas eigenwilliges Haustür-Schließsystem) eingelassen wurden.
Jetzt mußten wir uns erst mal das Fernsehprogramm angucken (die Heimleiterin hat irgendwas von "Deutscher Welle" gesagt (??)).
Das erste, was kam war Highlander II mit schwedischen Untertiteln… Mußten wir uns erst mal angucken, auch wenn kurz die Heimleiterin rein kam und fragte: "Is everything okay?"…
Dann haben wir nach ner halben Stunde geguckt, was denn die "Deutsche Welle" war: ein anscheinend italienischer Kanal, der nur über Deutschland berichtet… Toll!
Gegen 23.30h gingen wir schlafen: der etwas ältere Australier und der Schwede lagen da schon und als wir am nächsten Morgen (also heute) aufstanden, waren die beiden auch schon nicht mehr da.
Nach einer ausgiebigen Dusche und Wäsche meinerseits, begann ich dieses Buch weiter zu schreiben.
Danach begaben wir uns zur Straßenbahn, um zum Bahnhof zu gelangen; Tom machte dabei die Bekanntschaft mit einer älteren, stinkenden Dame.
Jetzt sitzen wir im Zug nach Helsingbørg und warten auf die Abfahrt, die in etwa 10 Minuten sein wird.
Sind gegen 15.00h in Kopenhagen angekommen. Haben zuerst den falschen Bus genommen, es dann aber doch geschafft zum größten Youthhostel Europas zu gelangen. Hier haben wir auch sofort einen Platz bekommen und eingecheckt. Nachdem wir unsere Routenplanung für die letzte Etappe unserer Fahrt beendet hatten, ging es mit dem Bus zurück ins Zentrum. Dort bummelten wir ein bißchen durch die Fußgängerzone. Bei einem türkischen Imbiss gabs dann was zu futtern und danach ein echtes dänisches Eis. In Kopenhagen war verglichen mit den anderen Hauptstädten Skandinaviens am meisten los. Viele Straßenmusiker prägen das Stadtbild. Auf einem Platz muß wohl eine Art Fest stattgefunden haben. In einem Zelt spielte eine türkische Band zünftige Folklore unterstützt von einer Buchtänzerin. Sonst gab es dort viele seltsame Objekte aus Schrott: Flugmaschinen, Elefanten und lauter schräger Konstruktionen. Beim Weitergehen stoßen wir dann auf das Erotikmuseum, das uns aber dem überhöhten Eintritt nicht Wert war.
Die Busfahrt war im wahrsten Sinne des Wortes spannend. Ich habe nur auf die Endhaltestelle geguckt und ich glaubt mich zu erinnern, daß wir dort in den Bus zur Jugendherberge umgestiegen sind. Als der Bus am Bahnhof hielt, sind wir einfach eingestiegen. Er brachte uns durch verwinkelte Straßen und am Wasser vorbei. Das konnte nicht richtig sein. Wir malten uns schon aus, wie wir verirrt und verwirrt durch Kopenhagen liefen. Doch gerade in diesem Moment sagte Schumi "Die Bank hab ich schon mal gesehen!&quot;; und richtig: wir waren am richtigen Ort. Wir sind jetzt in der Jugendherberge, 10.45h. Betreibe zur Zeit Multitasking, indem ich mich mit unserem rumänischen Zimmergenossen unterhalte und diesen Bericht schreibe.

== Tag 17, Di, 03.09.1996, 18.30h

Sind gerade vom Imbiss in Kiel zurückgekommen und haben jetzt jede Menge Zeit hier im Hauptbahnhof den Bericht weiter zu schreiben…
Nach einer ruhigen Nacht im Youth-Hostel in Kopenhagen, haben wir uns - nach einer kurzen Wäsche (war alles ziemlich dreckig dort) - für das dort angebotene Frühstücksbuffet für 38 DKr entschieden. Keine gute Wahl, wie sich nachher herausstellte: die Auswahl war klein und das Essen für den Preis zu schlecht. Ich erinnere mich nur noch an diese ekelig strahlend-pinkfarbene Salami… das Auge ißt schließlich mit…
Dann gings auf mit dem Bus zur Innenstadt, noch ein paar Anrufe getätigt und schon waren wir in Kopenhagen Hbf.
(Nee, die Anrufe waren am Abend vorher, aber egal) Und wieder ging es durch die Innenstadt. Am Hafen vorbei kamen wir bald an der dänisch-königlichen Residenz heraus. Ist schon ziemlich blöd, wenn die ganzen Leute im Vorgarten rum rennen. Hier gabs zwar keine zackige Wachablösung, aber dafür witzige Pelzmützen tz bestaunen. Weiter ging es nach nebenan in den Dom. Via gotische Kirche gelangten wir endlich zur lang ersehnten, weltberühmten und atemberaubend riesigen Meerjungfrau aus Hans Christian Andersens Märchen.
Zurück zur Innenstadt liefen wir noch durch das Fort, in dem tatsächlich die Stadtkommandatur der dänischen Armee untergebracht ist. Bei Super-Brugsen versorgten wir uns dann mit dem Nötigsten, sprich: Brot, Wurst, Käse, Schoko und Kakao. Total inne Wurst (!) ließen wir uns in einer "Friß oder stirb"-Pizzahöhle nieder. Super Salatbuffet und recht ordentlicher Pizza! Nachdem wir (natürlich! hätte ich mal gewettet!) vergeblich auf die Geräusche aus der Tiefe gewartet haben (Geräuschinstallation vor dem Rathaus), haben wir unsere Rucksäcke aus dem Interrailcenter, das um 16.00h wieder aufmachte, geholt und den nächsten IC nach Odense genommen. Am Busbahnhof stiegen wir zwar in die richtige Linie, aber in falscher Richtung ein, doch der freundliche Däne hinterm Steuer brachte uns gestikulierend und schulterklopfend zur anderen Straßenseite und gab uns dort an seine Kollegin ab.
20.03h erreichten wir die Jugendherberge: ein alter Gutshof, und natürlich die Rezeption seit 3 Minuten geschlossen. Doch wer klopft dem wir aufgetan und so erhielten wir doch noch unsere Chipkarten, ohne die gar nichts ging. Nach dem selbst mitgebrachten Abendbrot im Innenhof machten wir noch einen kleinen Spaziergang durch ein kleines Wäldchen. Heute morgen besuchten wir den alten Knud. Knud lebt heute in der Domkirche von Odense. Er ist mit den Jahren etwas dünn geworden. Das liegt wahrscheinlich daran, daß man ihm so um 1000 und noch was einen auf die Glocke gehauen hat, als er noch König der Dänen war. Ins Eisenbahnmuseum sind wir dann wegen unseres Scanrail-Passes für Nüsse rein gekommen. Das war auch gut so, denn wir waren total Pleite.
Wir konnten nicht einmal mehr den IC-Zuschlag für den Zug nach Fredericia kaufen. Ich hab dann für eine Karte meinen letzten 10DM-Schein geopfert. Wegen akutem Geldmangel mußte Schumi nichts bezahlen (und ich war mir auch nicht mehr so sicher, ob wir überhaupt hätten zahlen müssen). In Fredericia nahmen wir den Zug bis zur dänisch-deutschen Grenze ohne Zuschlag. Doch eine Station vor Flensburg hat es uns dann doch nicht mehr gereicht - das Geld. Bis Flensburg mußten wir nämlich ein 30 DKr-Ticket kaufen: also doch noch Geld abholen. Schumi hat für seinen Eurocheque dann auch selbiges bei der Post besorgt. Mit der Bimmelbahn ging es dann weiter nach Kiel, nachdem wir Deutschgeld von der Post und Auskunft und Karten am DB-Schalter erhalten hatten.
In Kiel kauften wir uns zuerst unser Guten-Abend-Tickets und suchten einen Ort der Speisung. Mehmed sollte unserem leichten Hungergefühl Abhilfe leisten. Jetzt ist es 19.00h und wir sitzen abfahrbereit für unsere letzt Etappe im IC nach Dortmund und so endet unsere doch relativ Ereignisreiche Interrailtour durch Skandinavien…
Wenn Ihr Kommentare, Fragen, oder Anmerkungen habt… nur zu!